# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleEnemyUnit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BattleEnemyUnit.proto',
  package='',
  serialized_pb=_b('\n\x15\x42\x61ttleEnemyUnit.proto\"\xac\x01\n\x0f\x42\x61ttleEnemyUnit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\x05\x12\x0b\n\x03\x63ri\x18\x07 \x01(\x08\x12\x0b\n\x03hit\x18\x08 \x01(\x08\x12\x0e\n\x06\x64\x61mage\x18\t \x01(\x05\x12\x0e\n\x06shield\x18\n \x01(\x05\x12\x17\n\x0f\x65nemyeffecttype\x18\x0b \x01(\x05\x12\x18\n\x10\x65nemyeffectvalue\x18\x0c \x01(\x05\x12\x12\n\nreservepos\x18\r \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATTLEENEMYUNIT = _descriptor.Descriptor(
  name='BattleEnemyUnit',
  full_name='BattleEnemyUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BattleEnemyUnit.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='BattleEnemyUnit.role', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cri', full_name='BattleEnemyUnit.cri', index=2,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hit', full_name='BattleEnemyUnit.hit', index=3,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='damage', full_name='BattleEnemyUnit.damage', index=4,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shield', full_name='BattleEnemyUnit.shield', index=5,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enemyeffecttype', full_name='BattleEnemyUnit.enemyeffecttype', index=6,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enemyeffectvalue', full_name='BattleEnemyUnit.enemyeffectvalue', index=7,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reservepos', full_name='BattleEnemyUnit.reservepos', index=8,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['BattleEnemyUnit'] = _BATTLEENEMYUNIT

BattleEnemyUnit = _reflection.GeneratedProtocolMessageType('BattleEnemyUnit', (_message.Message,), dict(
  DESCRIPTOR = _BATTLEENEMYUNIT,
  __module__ = 'BattleEnemyUnit_pb2'
  # @@protoc_insertion_point(class_scope:BattleEnemyUnit)
  ))
_sym_db.RegisterMessage(BattleEnemyUnit)


# @@protoc_insertion_point(module_scope)
