# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleAction_pb2
import TacticInfo_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BattleInfo.proto',
  package='',
  serialized_pb=_b('\n\x10\x42\x61ttleInfo.proto\x1a\x12\x42\x61ttleAction.proto\x1a\x10TacticInfo.proto\"\xb4\x01\n\nBattleInfo\x12\x10\n\x08\x62\x61ttleid\x18\x01 \x01(\t\x12\x12\n\nbattletype\x18\x02 \x01(\x05\x12\x1e\n\tattackTac\x18\x03 \x01(\x0b\x32\x0b.TacticInfo\x12\x1e\n\tdefendTac\x18\x04 \x01(\x0b\x32\x0b.TacticInfo\x12!\n\nactionlist\x18\x05 \x03(\x0b\x32\r.BattleAction\x12\r\n\x05score\x18\x06 \x01(\x05\x12\x0e\n\x06isauto\x18\x07 \x01(\x08')
  ,
  dependencies=[BattleAction_pb2.DESCRIPTOR,TacticInfo_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATTLEINFO = _descriptor.Descriptor(
  name='BattleInfo',
  full_name='BattleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='battleid', full_name='BattleInfo.battleid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battletype', full_name='BattleInfo.battletype', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attackTac', full_name='BattleInfo.attackTac', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defendTac', full_name='BattleInfo.defendTac', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionlist', full_name='BattleInfo.actionlist', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='BattleInfo.score', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isauto', full_name='BattleInfo.isauto', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=239,
)

_BATTLEINFO.fields_by_name['attackTac'].message_type = TacticInfo_pb2._TACTICINFO
_BATTLEINFO.fields_by_name['defendTac'].message_type = TacticInfo_pb2._TACTICINFO
_BATTLEINFO.fields_by_name['actionlist'].message_type = BattleAction_pb2._BATTLEACTION
DESCRIPTOR.message_types_by_name['BattleInfo'] = _BATTLEINFO

BattleInfo = _reflection.GeneratedProtocolMessageType('BattleInfo', (_message.Message,), dict(
  DESCRIPTOR = _BATTLEINFO,
  __module__ = 'BattleInfo_pb2'
  # @@protoc_insertion_point(class_scope:BattleInfo)
  ))
_sym_db.RegisterMessage(BattleInfo)


# @@protoc_insertion_point(module_scope)
