# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleSpirits.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BattleSpirits.proto',
  package='',
  serialized_pb=_b('\n\x13\x42\x61ttleSpirits.proto\"\xa2\x03\n\rBattleSpirits\x12\r\n\x02id\x18\x01 \x01(\t:\x01\x30\x12\x11\n\tspiritsid\x18\x02 \x01(\x05\x12\x0f\n\x07skillid\x18\x03 \x01(\x05\x12\x14\n\x0cslideskillid\x18\x04 \x01(\x05\x12\x13\n\x0b\x66uryskillid\x18\x05 \x01(\x05\x12\x15\n\rleaderskillid\x18\x06 \x01(\x05\x12\x10\n\x08talentid\x18\x07 \x01(\x05\x12\x0f\n\x07upgrade\x18\x08 \x01(\x05\x12\x10\n\x08reformed\x18\t \x01(\x05\x12\x0c\n\x04skin\x18\n \x01(\x05\x12\n\n\x02hp\x18\x0b \x01(\x05\x12\r\n\x05maxhp\x18\x0c \x01(\x05\x12\r\n\x05speed\x18\r \x01(\x05\x12\x11\n\tfurypoint\x18\x0e \x01(\x05\x12\x14\n\x0cpropertylist\x18\x0f \x03(\x05\x12\x18\n\x10\x62\x61sepropertylist\x18\x10 \x03(\x05\x12\x18\n\x10\x62uffpropertylist\x18\x11 \x03(\x05\x12\x14\n\x0cslideacctime\x18\x12 \x01(\x05\x12\x13\n\x0bvertigotime\x18\x13 \x01(\x05\x12\x12\n\nshieldtime\x18\x14 \x01(\x05\x12\x13\n\x0bshieldvalue\x18\x15 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATTLESPIRITS = _descriptor.Descriptor(
  name='BattleSpirits',
  full_name='BattleSpirits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BattleSpirits.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("0").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spiritsid', full_name='BattleSpirits.spiritsid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skillid', full_name='BattleSpirits.skillid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slideskillid', full_name='BattleSpirits.slideskillid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='furyskillid', full_name='BattleSpirits.furyskillid', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leaderskillid', full_name='BattleSpirits.leaderskillid', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='talentid', full_name='BattleSpirits.talentid', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upgrade', full_name='BattleSpirits.upgrade', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reformed', full_name='BattleSpirits.reformed', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skin', full_name='BattleSpirits.skin', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='BattleSpirits.hp', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxhp', full_name='BattleSpirits.maxhp', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='BattleSpirits.speed', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='furypoint', full_name='BattleSpirits.furypoint', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='propertylist', full_name='BattleSpirits.propertylist', index=14,
      number=15, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='basepropertylist', full_name='BattleSpirits.basepropertylist', index=15,
      number=16, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffpropertylist', full_name='BattleSpirits.buffpropertylist', index=16,
      number=17, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slideacctime', full_name='BattleSpirits.slideacctime', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertigotime', full_name='BattleSpirits.vertigotime', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shieldtime', full_name='BattleSpirits.shieldtime', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shieldvalue', full_name='BattleSpirits.shieldvalue', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=442,
)

DESCRIPTOR.message_types_by_name['BattleSpirits'] = _BATTLESPIRITS

BattleSpirits = _reflection.GeneratedProtocolMessageType('BattleSpirits', (_message.Message,), dict(
  DESCRIPTOR = _BATTLESPIRITS,
  __module__ = 'BattleSpirits_pb2'
  # @@protoc_insertion_point(class_scope:BattleSpirits)
  ))
_sym_db.RegisterMessage(BattleSpirits)


# @@protoc_insertion_point(module_scope)
