# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleSelfUnit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BattleSelfUnit.proto',
  package='',
  serialized_pb=_b('\n\x14\x42\x61ttleSelfUnit.proto\"K\n\x0e\x42\x61ttleSelfUnit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rowneffecttype\x18\n \x01(\x05\x12\x16\n\x0eowneffectparam\x18\x0b \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATTLESELFUNIT = _descriptor.Descriptor(
  name='BattleSelfUnit',
  full_name='BattleSelfUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BattleSelfUnit.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owneffecttype', full_name='BattleSelfUnit.owneffecttype', index=1,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owneffectparam', full_name='BattleSelfUnit.owneffectparam', index=2,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['BattleSelfUnit'] = _BATTLESELFUNIT

BattleSelfUnit = _reflection.GeneratedProtocolMessageType('BattleSelfUnit', (_message.Message,), dict(
  DESCRIPTOR = _BATTLESELFUNIT,
  __module__ = 'BattleSelfUnit_pb2'
  # @@protoc_insertion_point(class_scope:BattleSelfUnit)
  ))
_sym_db.RegisterMessage(BattleSelfUnit)


# @@protoc_insertion_point(module_scope)
