# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleAction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleEnemyUnit_pb2
import BattleSelfUnit_pb2
import BattleOneUnit_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BattleAction.proto',
  package='',
  serialized_pb=_b('\n\x12\x42\x61ttleAction.proto\x1a\x15\x42\x61ttleEnemyUnit.proto\x1a\x14\x42\x61ttleSelfUnit.proto\x1a\x13\x42\x61ttleOneUnit.proto\"\xcf\x01\n\x0c\x42\x61ttleAction\x12\x10\n\x08\x61ttackid\x18\x01 \x01(\t\x12\x12\n\nattackrole\x18\x02 \x01(\x05\x12\x0f\n\x07skillid\x18\x03 \x01(\x05\x12\x12\n\nskillparam\x18\x04 \x01(\x05\x12$\n\ntargetlist\x18\x05 \x03(\x0b\x32\x10.BattleEnemyUnit\x12&\n\rowneffectlist\x18\x06 \x03(\x0b\x32\x0f.BattleSelfUnit\x12&\n\x0e\x61llspiritslist\x18\x07 \x03(\x0b\x32\x0e.BattleOneUnit')
  ,
  dependencies=[BattleEnemyUnit_pb2.DESCRIPTOR,BattleSelfUnit_pb2.DESCRIPTOR,BattleOneUnit_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATTLEACTION = _descriptor.Descriptor(
  name='BattleAction',
  full_name='BattleAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attackid', full_name='BattleAction.attackid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attackrole', full_name='BattleAction.attackrole', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skillid', full_name='BattleAction.skillid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skillparam', full_name='BattleAction.skillparam', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetlist', full_name='BattleAction.targetlist', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owneffectlist', full_name='BattleAction.owneffectlist', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allspiritslist', full_name='BattleAction.allspiritslist', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=296,
)

_BATTLEACTION.fields_by_name['targetlist'].message_type = BattleEnemyUnit_pb2._BATTLEENEMYUNIT
_BATTLEACTION.fields_by_name['owneffectlist'].message_type = BattleSelfUnit_pb2._BATTLESELFUNIT
_BATTLEACTION.fields_by_name['allspiritslist'].message_type = BattleOneUnit_pb2._BATTLEONEUNIT
DESCRIPTOR.message_types_by_name['BattleAction'] = _BATTLEACTION

BattleAction = _reflection.GeneratedProtocolMessageType('BattleAction', (_message.Message,), dict(
  DESCRIPTOR = _BATTLEACTION,
  __module__ = 'BattleAction_pb2'
  # @@protoc_insertion_point(class_scope:BattleAction)
  ))
_sym_db.RegisterMessage(BattleAction)


# @@protoc_insertion_point(module_scope)
