# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleOneUnit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BattleOneUnit.proto',
  package='',
  serialized_pb=_b('\n\x13\x42\x61ttleOneUnit.proto\"*\n\x0b\x43\x45\x66\x66\x65\x63tData\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\x05\"\x8f\x01\n\rBattleOneUnit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\x05\x12\n\n\x02hp\x18\x03 \x01(\x05\x12\r\n\x05maxhp\x18\x04 \x01(\x05\x12\x11\n\tfurypoint\x18\x05 \x01(\x05\x12\x14\n\x0cslideacctime\x18\x06 \x01(\x05\x12 \n\neffectlist\x18\x07 \x03(\x0b\x32\x0c.CEffectData')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CEFFECTDATA = _descriptor.Descriptor(
  name='CEffectData',
  full_name='CEffectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CEffectData.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='CEffectData.param', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=65,
)


_BATTLEONEUNIT = _descriptor.Descriptor(
  name='BattleOneUnit',
  full_name='BattleOneUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BattleOneUnit.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='BattleOneUnit.role', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='BattleOneUnit.hp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxhp', full_name='BattleOneUnit.maxhp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='furypoint', full_name='BattleOneUnit.furypoint', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slideacctime', full_name='BattleOneUnit.slideacctime', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='effectlist', full_name='BattleOneUnit.effectlist', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=211,
)

_BATTLEONEUNIT.fields_by_name['effectlist'].message_type = _CEFFECTDATA
DESCRIPTOR.message_types_by_name['CEffectData'] = _CEFFECTDATA
DESCRIPTOR.message_types_by_name['BattleOneUnit'] = _BATTLEONEUNIT

CEffectData = _reflection.GeneratedProtocolMessageType('CEffectData', (_message.Message,), dict(
  DESCRIPTOR = _CEFFECTDATA,
  __module__ = 'BattleOneUnit_pb2'
  # @@protoc_insertion_point(class_scope:CEffectData)
  ))
_sym_db.RegisterMessage(CEffectData)

BattleOneUnit = _reflection.GeneratedProtocolMessageType('BattleOneUnit', (_message.Message,), dict(
  DESCRIPTOR = _BATTLEONEUNIT,
  __module__ = 'BattleOneUnit_pb2'
  # @@protoc_insertion_point(class_scope:BattleOneUnit)
  ))
_sym_db.RegisterMessage(BattleOneUnit)


# @@protoc_insertion_point(module_scope)
