# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceAllEquipmentInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceAllEquipmentInfo.proto',
  package='',
  serialized_pb=_b('\n\x19\x44\x63\x65\x41llEquipmentInfo.proto\"\x15\n\x13\x44\x63\x65\x41llEquipmentInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEALLEQUIPMENTINFO = _descriptor.Descriptor(
  name='DceAllEquipmentInfo',
  full_name='DceAllEquipmentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['DceAllEquipmentInfo'] = _DCEALLEQUIPMENTINFO

DceAllEquipmentInfo = _reflection.GeneratedProtocolMessageType('DceAllEquipmentInfo', (_message.Message,), dict(
  DESCRIPTOR = _DCEALLEQUIPMENTINFO,
  __module__ = 'DceAllEquipmentInfo_pb2'
  # @@protoc_insertion_point(class_scope:DceAllEquipmentInfo)
  ))
_sym_db.RegisterMessage(DceAllEquipmentInfo)


# @@protoc_insertion_point(module_scope)
