# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceArenaOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceArenaOpt.proto',
  package='',
  serialized_pb=_b('\n\x11\x44\x63\x65\x41renaOpt.proto\"\x1b\n\x0b\x44\x63\x65\x41renaOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEARENAOPT = _descriptor.Descriptor(
  name='DceArenaOpt',
  full_name='DceArenaOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceArenaOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['DceArenaOpt'] = _DCEARENAOPT

DceArenaOpt = _reflection.GeneratedProtocolMessageType('DceArenaOpt', (_message.Message,), dict(
  DESCRIPTOR = _DCEARENAOPT,
  __module__ = 'DceArenaOpt_pb2'
  # @@protoc_insertion_point(class_scope:DceArenaOpt)
  ))
_sym_db.RegisterMessage(DceArenaOpt)


# @@protoc_insertion_point(module_scope)
