# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceBattleStart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceBattleStart.proto',
  package='',
  serialized_pb=_b('\n\x14\x44\x63\x65\x42\x61ttleStart.proto\"V\n\x0e\x44\x63\x65\x42\x61ttleStart\x12\x10\n\x08targetID\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x12\n\ntargetRank\x18\x03 \x01(\x05\x12\x10\n\x08selfRank\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEBATTLESTART = _descriptor.Descriptor(
  name='DceBattleStart',
  full_name='DceBattleStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetID', full_name='DceBattleStart.targetID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DceBattleStart.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetRank', full_name='DceBattleStart.targetRank', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='selfRank', full_name='DceBattleStart.selfRank', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['DceBattleStart'] = _DCEBATTLESTART

DceBattleStart = _reflection.GeneratedProtocolMessageType('DceBattleStart', (_message.Message,), dict(
  DESCRIPTOR = _DCEBATTLESTART,
  __module__ = 'DceBattleStart_pb2'
  # @@protoc_insertion_point(class_scope:DceBattleStart)
  ))
_sym_db.RegisterMessage(DceBattleStart)


# @@protoc_insertion_point(module_scope)
