# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceBattleOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceBattleOpt.proto',
  package='',
  serialized_pb=_b('\n\x12\x44\x63\x65\x42\x61ttleOpt.proto\"a\n\x0c\x44\x63\x65\x42\x61ttleOpt\x12\x10\n\x08\x62\x61ttleid\x18\x01 \x01(\t\x12\x10\n\x08opt_type\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\t\x12\r\n\x05param\x18\x04 \x01(\x05\x12\x12\n\ntransparam\x18\x05 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEBATTLEOPT = _descriptor.Descriptor(
  name='DceBattleOpt',
  full_name='DceBattleOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='battleid', full_name='DceBattleOpt.battleid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opt_type', full_name='DceBattleOpt.opt_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='DceBattleOpt.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DceBattleOpt.param', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transparam', full_name='DceBattleOpt.transparam', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['DceBattleOpt'] = _DCEBATTLEOPT

DceBattleOpt = _reflection.GeneratedProtocolMessageType('DceBattleOpt', (_message.Message,), dict(
  DESCRIPTOR = _DCEBATTLEOPT,
  __module__ = 'DceBattleOpt_pb2'
  # @@protoc_insertion_point(class_scope:DceBattleOpt)
  ))
_sym_db.RegisterMessage(DceBattleOpt)


# @@protoc_insertion_point(module_scope)
