# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceCombineSpiritDebris.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceCombineSpiritDebris.proto',
  package='',
  serialized_pb=_b('\n\x1c\x44\x63\x65\x43ombineSpiritDebris.proto\"2\n\x16\x44\x63\x65\x43ombineSpiritDebris\x12\n\n\x02id\x18\x01 \x03(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCECOMBINESPIRITDEBRIS = _descriptor.Descriptor(
  name='DceCombineSpiritDebris',
  full_name='DceCombineSpiritDebris',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DceCombineSpiritDebris.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DceCombineSpiritDebris.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['DceCombineSpiritDebris'] = _DCECOMBINESPIRITDEBRIS

DceCombineSpiritDebris = _reflection.GeneratedProtocolMessageType('DceCombineSpiritDebris', (_message.Message,), dict(
  DESCRIPTOR = _DCECOMBINESPIRITDEBRIS,
  __module__ = 'DceCombineSpiritDebris_pb2'
  # @@protoc_insertion_point(class_scope:DceCombineSpiritDebris)
  ))
_sym_db.RegisterMessage(DceCombineSpiritDebris)


# @@protoc_insertion_point(module_scope)
