# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceChat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceChat.proto',
  package='',
  serialized_pb=_b('\n\rDceChat.proto\"(\n\x07\x44\x63\x65\x43hat\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCECHAT = _descriptor.Descriptor(
  name='DceChat',
  full_name='DceChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceChat.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='DceChat.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['DceChat'] = _DCECHAT

DceChat = _reflection.GeneratedProtocolMessageType('DceChat', (_message.Message,), dict(
  DESCRIPTOR = _DCECHAT,
  __module__ = 'DceChat_pb2'
  # @@protoc_insertion_point(class_scope:DceChat)
  ))
_sym_db.RegisterMessage(DceChat)


# @@protoc_insertion_point(module_scope)
