# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceCombineProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceCombineProto.proto',
  package='',
  serialized_pb=_b('\n\x15\x44\x63\x65\x43ombineProto.proto\"%\n\x0f\x44\x63\x65\x43ombineProto\x12\x12\n\nproto_list\x18\x01 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCECOMBINEPROTO = _descriptor.Descriptor(
  name='DceCombineProto',
  full_name='DceCombineProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_list', full_name='DceCombineProto.proto_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['DceCombineProto'] = _DCECOMBINEPROTO

DceCombineProto = _reflection.GeneratedProtocolMessageType('DceCombineProto', (_message.Message,), dict(
  DESCRIPTOR = _DCECOMBINEPROTO,
  __module__ = 'DceCombineProto_pb2'
  # @@protoc_insertion_point(class_scope:DceCombineProto)
  ))
_sym_db.RegisterMessage(DceCombineProto)


# @@protoc_insertion_point(module_scope)
