# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceDailyOlineAwardData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceDailyOlineAwardData.proto',
  package='',
  serialized_pb=_b('\n\x1c\x44\x63\x65\x44\x61ilyOlineAwardData.proto\"\x18\n\x16\x44\x63\x65\x44\x61ilyOlineAwardData')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEDAILYOLINEAWARDDATA = _descriptor.Descriptor(
  name='DceDailyOlineAwardData',
  full_name='DceDailyOlineAwardData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['DceDailyOlineAwardData'] = _DCEDAILYOLINEAWARDDATA

DceDailyOlineAwardData = _reflection.GeneratedProtocolMessageType('DceDailyOlineAwardData', (_message.Message,), dict(
  DESCRIPTOR = _DCEDAILYOLINEAWARDDATA,
  __module__ = 'DceDailyOlineAwardData_pb2'
  # @@protoc_insertion_point(class_scope:DceDailyOlineAwardData)
  ))
_sym_db.RegisterMessage(DceDailyOlineAwardData)


# @@protoc_insertion_point(module_scope)
