# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceDailyOlineGetAward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceDailyOlineGetAward.proto',
  package='',
  serialized_pb=_b('\n\x1b\x44\x63\x65\x44\x61ilyOlineGetAward.proto\"&\n\x15\x44\x63\x65\x44\x61ilyOlineGetAward\x12\r\n\x05\x62oxid\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEDAILYOLINEGETAWARD = _descriptor.Descriptor(
  name='DceDailyOlineGetAward',
  full_name='DceDailyOlineGetAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boxid', full_name='DceDailyOlineGetAward.boxid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['DceDailyOlineGetAward'] = _DCEDAILYOLINEGETAWARD

DceDailyOlineGetAward = _reflection.GeneratedProtocolMessageType('DceDailyOlineGetAward', (_message.Message,), dict(
  DESCRIPTOR = _DCEDAILYOLINEGETAWARD,
  __module__ = 'DceDailyOlineGetAward_pb2'
  # @@protoc_insertion_point(class_scope:DceDailyOlineGetAward)
  ))
_sym_db.RegisterMessage(DceDailyOlineGetAward)


# @@protoc_insertion_point(module_scope)
