# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceDugeonOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceDugeonOpt.proto',
  package='',
  serialized_pb=_b('\n\x12\x44\x63\x65\x44ugeonOpt.proto\"\x1c\n\x0c\x44\x63\x65\x44ugeonOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEDUGEONOPT = _descriptor.Descriptor(
  name='DceDugeonOpt',
  full_name='DceDugeonOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceDugeonOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['DceDugeonOpt'] = _DCEDUGEONOPT

DceDugeonOpt = _reflection.GeneratedProtocolMessageType('DceDugeonOpt', (_message.Message,), dict(
  DESCRIPTOR = _DCEDUGEONOPT,
  __module__ = 'DceDugeonOpt_pb2'
  # @@protoc_insertion_point(class_scope:DceDugeonOpt)
  ))
_sym_db.RegisterMessage(DceDugeonOpt)


# @@protoc_insertion_point(module_scope)
