# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceDailyActivityOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceDailyActivityOpt.proto',
  package='',
  serialized_pb=_b('\n\x19\x44\x63\x65\x44\x61ilyActivityOpt.proto\"2\n\x13\x44\x63\x65\x44\x61ilyActivityOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEDAILYACTIVITYOPT = _descriptor.Descriptor(
  name='DceDailyActivityOpt',
  full_name='DceDailyActivityOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceDailyActivityOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DceDailyActivityOpt.param', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['DceDailyActivityOpt'] = _DCEDAILYACTIVITYOPT

DceDailyActivityOpt = _reflection.GeneratedProtocolMessageType('DceDailyActivityOpt', (_message.Message,), dict(
  DESCRIPTOR = _DCEDAILYACTIVITYOPT,
  __module__ = 'DceDailyActivityOpt_pb2'
  # @@protoc_insertion_point(class_scope:DceDailyActivityOpt)
  ))
_sym_db.RegisterMessage(DceDailyActivityOpt)


# @@protoc_insertion_point(module_scope)
