# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceEquipmentDebrisList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceEquipmentDebrisList.proto',
  package='',
  serialized_pb=_b('\n\x1c\x44\x63\x65\x45quipmentDebrisList.proto\"\x18\n\x16\x44\x63\x65\x45quipmentDebrisList')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEEQUIPMENTDEBRISLIST = _descriptor.Descriptor(
  name='DceEquipmentDebrisList',
  full_name='DceEquipmentDebrisList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['DceEquipmentDebrisList'] = _DCEEQUIPMENTDEBRISLIST

DceEquipmentDebrisList = _reflection.GeneratedProtocolMessageType('DceEquipmentDebrisList', (_message.Message,), dict(
  DESCRIPTOR = _DCEEQUIPMENTDEBRISLIST,
  __module__ = 'DceEquipmentDebrisList_pb2'
  # @@protoc_insertion_point(class_scope:DceEquipmentDebrisList)
  ))
_sym_db.RegisterMessage(DceEquipmentDebrisList)


# @@protoc_insertion_point(module_scope)
