# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceEquipmentGearUp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceEquipmentGearUp.proto',
  package='',
  serialized_pb=_b('\n\x18\x44\x63\x65\x45quipmentGearUp.proto\".\n\x12\x44\x63\x65\x45quipmentGearUp\x12\x0b\n\x03oid\x18\x01 \x01(\t\x12\x0b\n\x03pos\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEEQUIPMENTGEARUP = _descriptor.Descriptor(
  name='DceEquipmentGearUp',
  full_name='DceEquipmentGearUp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oid', full_name='DceEquipmentGearUp.oid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='DceEquipmentGearUp.pos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['DceEquipmentGearUp'] = _DCEEQUIPMENTGEARUP

DceEquipmentGearUp = _reflection.GeneratedProtocolMessageType('DceEquipmentGearUp', (_message.Message,), dict(
  DESCRIPTOR = _DCEEQUIPMENTGEARUP,
  __module__ = 'DceEquipmentGearUp_pb2'
  # @@protoc_insertion_point(class_scope:DceEquipmentGearUp)
  ))
_sym_db.RegisterMessage(DceEquipmentGearUp)


# @@protoc_insertion_point(module_scope)
