# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceEquipmentRefine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceEquipmentRefine.proto',
  package='',
  serialized_pb=_b('\n\x18\x44\x63\x65\x45quipmentRefine.proto\"!\n\x12\x44\x63\x65\x45quipmentRefine\x12\x0b\n\x03oid\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEEQUIPMENTREFINE = _descriptor.Descriptor(
  name='DceEquipmentRefine',
  full_name='DceEquipmentRefine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oid', full_name='DceEquipmentRefine.oid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['DceEquipmentRefine'] = _DCEEQUIPMENTREFINE

DceEquipmentRefine = _reflection.GeneratedProtocolMessageType('DceEquipmentRefine', (_message.Message,), dict(
  DESCRIPTOR = _DCEEQUIPMENTREFINE,
  __module__ = 'DceEquipmentRefine_pb2'
  # @@protoc_insertion_point(class_scope:DceEquipmentRefine)
  ))
_sym_db.RegisterMessage(DceEquipmentRefine)


# @@protoc_insertion_point(module_scope)
