# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceGuildDismiss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceGuildDismiss.proto',
  package='',
  serialized_pb=_b('\n\x15\x44\x63\x65GuildDismiss.proto\"\x11\n\x0f\x44\x63\x65GuildDismiss')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEGUILDDISMISS = _descriptor.Descriptor(
  name='DceGuildDismiss',
  full_name='DceGuildDismiss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=42,
)

DESCRIPTOR.message_types_by_name['DceGuildDismiss'] = _DCEGUILDDISMISS

DceGuildDismiss = _reflection.GeneratedProtocolMessageType('DceGuildDismiss', (_message.Message,), dict(
  DESCRIPTOR = _DCEGUILDDISMISS,
  __module__ = 'DceGuildDismiss_pb2'
  # @@protoc_insertion_point(class_scope:DceGuildDismiss)
  ))
_sym_db.RegisterMessage(DceGuildDismiss)


# @@protoc_insertion_point(module_scope)
