# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceGuildLeaveMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceGuildLeaveMessage.proto',
  package='',
  serialized_pb=_b('\n\x1a\x44\x63\x65GuildLeaveMessage.proto\"3\n\x14\x44\x63\x65GuildLeaveMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEGUILDLEAVEMESSAGE = _descriptor.Descriptor(
  name='DceGuildLeaveMessage',
  full_name='DceGuildLeaveMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DceGuildLeaveMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='DceGuildLeaveMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['DceGuildLeaveMessage'] = _DCEGUILDLEAVEMESSAGE

DceGuildLeaveMessage = _reflection.GeneratedProtocolMessageType('DceGuildLeaveMessage', (_message.Message,), dict(
  DESCRIPTOR = _DCEGUILDLEAVEMESSAGE,
  __module__ = 'DceGuildLeaveMessage_pb2'
  # @@protoc_insertion_point(class_scope:DceGuildLeaveMessage)
  ))
_sym_db.RegisterMessage(DceGuildLeaveMessage)


# @@protoc_insertion_point(module_scope)
