# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceGuildCreate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceGuildCreate.proto',
  package='',
  serialized_pb=_b('\n\x14\x44\x63\x65GuildCreate.proto\"X\n\x0e\x44\x63\x65GuildCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x62\x61\x64ge\x18\x02 \x01(\x05\x12\x14\n\x0c\x61utoapproval\x18\x03 \x01(\x08\x12\x13\n\x0b\x64\x65\x63laration\x18\x04 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEGUILDCREATE = _descriptor.Descriptor(
  name='DceGuildCreate',
  full_name='DceGuildCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DceGuildCreate.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='badge', full_name='DceGuildCreate.badge', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='autoapproval', full_name='DceGuildCreate.autoapproval', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='declaration', full_name='DceGuildCreate.declaration', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['DceGuildCreate'] = _DCEGUILDCREATE

DceGuildCreate = _reflection.GeneratedProtocolMessageType('DceGuildCreate', (_message.Message,), dict(
  DESCRIPTOR = _DCEGUILDCREATE,
  __module__ = 'DceGuildCreate_pb2'
  # @@protoc_insertion_point(class_scope:DceGuildCreate)
  ))
_sym_db.RegisterMessage(DceGuildCreate)


# @@protoc_insertion_point(module_scope)
