# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceGuildKickMember.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceGuildKickMember.proto',
  package='',
  serialized_pb=_b('\n\x18\x44\x63\x65GuildKickMember.proto\"!\n\x12\x44\x63\x65GuildKickMember\x12\x0b\n\x03uid\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEGUILDKICKMEMBER = _descriptor.Descriptor(
  name='DceGuildKickMember',
  full_name='DceGuildKickMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='DceGuildKickMember.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['DceGuildKickMember'] = _DCEGUILDKICKMEMBER

DceGuildKickMember = _reflection.GeneratedProtocolMessageType('DceGuildKickMember', (_message.Message,), dict(
  DESCRIPTOR = _DCEGUILDKICKMEMBER,
  __module__ = 'DceGuildKickMember_pb2'
  # @@protoc_insertion_point(class_scope:DceGuildKickMember)
  ))
_sym_db.RegisterMessage(DceGuildKickMember)


# @@protoc_insertion_point(module_scope)
