# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceGuildData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceGuildData.proto',
  package='',
  serialized_pb=_b('\n\x12\x44\x63\x65GuildData.proto\"\x1b\n\x0c\x44\x63\x65GuildData\x12\x0b\n\x03way\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEGUILDDATA = _descriptor.Descriptor(
  name='DceGuildData',
  full_name='DceGuildData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='way', full_name='DceGuildData.way', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['DceGuildData'] = _DCEGUILDDATA

DceGuildData = _reflection.GeneratedProtocolMessageType('DceGuildData', (_message.Message,), dict(
  DESCRIPTOR = _DCEGUILDDATA,
  __module__ = 'DceGuildData_pb2'
  # @@protoc_insertion_point(class_scope:DceGuildData)
  ))
_sym_db.RegisterMessage(DceGuildData)


# @@protoc_insertion_point(module_scope)
