# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceInstituteOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceInstituteOpt.proto',
  package='',
  serialized_pb=_b('\n\x15\x44\x63\x65InstituteOpt.proto\"4\n\x0f\x44\x63\x65InstituteOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x13\n\x0binstituteid\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEINSTITUTEOPT = _descriptor.Descriptor(
  name='DceInstituteOpt',
  full_name='DceInstituteOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceInstituteOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instituteid', full_name='DceInstituteOpt.instituteid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['DceInstituteOpt'] = _DCEINSTITUTEOPT

DceInstituteOpt = _reflection.GeneratedProtocolMessageType('DceInstituteOpt', (_message.Message,), dict(
  DESCRIPTOR = _DCEINSTITUTEOPT,
  __module__ = 'DceInstituteOpt_pb2'
  # @@protoc_insertion_point(class_scope:DceInstituteOpt)
  ))
_sym_db.RegisterMessage(DceInstituteOpt)


# @@protoc_insertion_point(module_scope)
