# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceQueryUserInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceQueryUserInfo.proto',
  package='',
  serialized_pb=_b('\n\x16\x44\x63\x65QueryUserInfo.proto\"\x1f\n\x10\x44\x63\x65QueryUserInfo\x12\x0b\n\x03uid\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEQUERYUSERINFO = _descriptor.Descriptor(
  name='DceQueryUserInfo',
  full_name='DceQueryUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='DceQueryUserInfo.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['DceQueryUserInfo'] = _DCEQUERYUSERINFO

DceQueryUserInfo = _reflection.GeneratedProtocolMessageType('DceQueryUserInfo', (_message.Message,), dict(
  DESCRIPTOR = _DCEQUERYUSERINFO,
  __module__ = 'DceQueryUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:DceQueryUserInfo)
  ))
_sym_db.RegisterMessage(DceQueryUserInfo)


# @@protoc_insertion_point(module_scope)
