# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceShowFormationInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceShowFormationInfo.proto',
  package='',
  serialized_pb=_b('\n\x1a\x44\x63\x65ShowFormationInfo.proto\"\x16\n\x14\x44\x63\x65ShowFormationInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCESHOWFORMATIONINFO = _descriptor.Descriptor(
  name='DceShowFormationInfo',
  full_name='DceShowFormationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['DceShowFormationInfo'] = _DCESHOWFORMATIONINFO

DceShowFormationInfo = _reflection.GeneratedProtocolMessageType('DceShowFormationInfo', (_message.Message,), dict(
  DESCRIPTOR = _DCESHOWFORMATIONINFO,
  __module__ = 'DceShowFormationInfo_pb2'
  # @@protoc_insertion_point(class_scope:DceShowFormationInfo)
  ))
_sym_db.RegisterMessage(DceShowFormationInfo)


# @@protoc_insertion_point(module_scope)
