# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceSummonInterface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceSummonInterface.proto',
  package='',
  serialized_pb=_b('\n\x18\x44\x63\x65SummonInterface.proto\"\x14\n\x12\x44\x63\x65SummonInterface')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCESUMMONINTERFACE = _descriptor.Descriptor(
  name='DceSummonInterface',
  full_name='DceSummonInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['DceSummonInterface'] = _DCESUMMONINTERFACE

DceSummonInterface = _reflection.GeneratedProtocolMessageType('DceSummonInterface', (_message.Message,), dict(
  DESCRIPTOR = _DCESUMMONINTERFACE,
  __module__ = 'DceSummonInterface_pb2'
  # @@protoc_insertion_point(class_scope:DceSummonInterface)
  ))
_sym_db.RegisterMessage(DceSummonInterface)


# @@protoc_insertion_point(module_scope)
