# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceSuitList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceSuitList.proto',
  package='',
  serialized_pb=_b('\n\x11\x44\x63\x65SuitList.proto\"\r\n\x0b\x44\x63\x65SuitList')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCESUITLIST = _descriptor.Descriptor(
  name='DceSuitList',
  full_name='DceSuitList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=34,
)

DESCRIPTOR.message_types_by_name['DceSuitList'] = _DCESUITLIST

DceSuitList = _reflection.GeneratedProtocolMessageType('DceSuitList', (_message.Message,), dict(
  DESCRIPTOR = _DCESUITLIST,
  __module__ = 'DceSuitList_pb2'
  # @@protoc_insertion_point(class_scope:DceSuitList)
  ))
_sym_db.RegisterMessage(DceSuitList)


# @@protoc_insertion_point(module_scope)
