# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceSetRole.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceSetRole.proto',
  package='',
  serialized_pb=_b('\n\x10\x44\x63\x65SetRole.proto\"7\n\nDceSetRole\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05param\x18\x03 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCESETROLE = _descriptor.Descriptor(
  name='DceSetRole',
  full_name='DceSetRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceSetRole.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='DceSetRole.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DceSetRole.param', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['DceSetRole'] = _DCESETROLE

DceSetRole = _reflection.GeneratedProtocolMessageType('DceSetRole', (_message.Message,), dict(
  DESCRIPTOR = _DCESETROLE,
  __module__ = 'DceSetRole_pb2'
  # @@protoc_insertion_point(class_scope:DceSetRole)
  ))
_sym_db.RegisterMessage(DceSetRole)


# @@protoc_insertion_point(module_scope)
