# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceStorageList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceStorageList.proto',
  package='',
  serialized_pb=_b('\n\x14\x44\x63\x65StorageList.proto\",\n\x0e\x44\x63\x65StorageList\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.StorageType*,\n\x0bStorageType\x12\x0f\n\x0bINVALID_BAG\x10\x00\x12\x0c\n\x08ITEM_BAG\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STORAGETYPE = _descriptor.EnumDescriptor(
  name='StorageType',
  full_name='StorageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_BAG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_BAG', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=70,
  serialized_end=114,
)
_sym_db.RegisterEnumDescriptor(_STORAGETYPE)

StorageType = enum_type_wrapper.EnumTypeWrapper(_STORAGETYPE)
INVALID_BAG = 0
ITEM_BAG = 1



_DCESTORAGELIST = _descriptor.Descriptor(
  name='DceStorageList',
  full_name='DceStorageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceStorageList.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)

_DCESTORAGELIST.fields_by_name['type'].enum_type = _STORAGETYPE
DESCRIPTOR.message_types_by_name['DceStorageList'] = _DCESTORAGELIST
DESCRIPTOR.enum_types_by_name['StorageType'] = _STORAGETYPE

DceStorageList = _reflection.GeneratedProtocolMessageType('DceStorageList', (_message.Message,), dict(
  DESCRIPTOR = _DCESTORAGELIST,
  __module__ = 'DceStorageList_pb2'
  # @@protoc_insertion_point(class_scope:DceStorageList)
  ))
_sym_db.RegisterMessage(DceStorageList)


# @@protoc_insertion_point(module_scope)
