# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceShowSingleSpiritInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceShowSingleSpiritInfo.proto',
  package='',
  serialized_pb=_b('\n\x1d\x44\x63\x65ShowSingleSpiritInfo.proto\"%\n\x17\x44\x63\x65ShowSingleSpiritInfo\x12\n\n\x02id\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCESHOWSINGLESPIRITINFO = _descriptor.Descriptor(
  name='DceShowSingleSpiritInfo',
  full_name='DceShowSingleSpiritInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DceShowSingleSpiritInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['DceShowSingleSpiritInfo'] = _DCESHOWSINGLESPIRITINFO

DceShowSingleSpiritInfo = _reflection.GeneratedProtocolMessageType('DceShowSingleSpiritInfo', (_message.Message,), dict(
  DESCRIPTOR = _DCESHOWSINGLESPIRITINFO,
  __module__ = 'DceShowSingleSpiritInfo_pb2'
  # @@protoc_insertion_point(class_scope:DceShowSingleSpiritInfo)
  ))
_sym_db.RegisterMessage(DceShowSingleSpiritInfo)


# @@protoc_insertion_point(module_scope)
