# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceStageAward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceStageAward.proto',
  package='',
  serialized_pb=_b('\n\x13\x44\x63\x65StageAward.proto\"A\n\rDceStageAward\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x11\n\tchapterid\x18\x02 \x01(\x05\x12\x0f\n\x07sceneid\x18\x03 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCESTAGEAWARD = _descriptor.Descriptor(
  name='DceStageAward',
  full_name='DceStageAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceStageAward.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chapterid', full_name='DceStageAward.chapterid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sceneid', full_name='DceStageAward.sceneid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['DceStageAward'] = _DCESTAGEAWARD

DceStageAward = _reflection.GeneratedProtocolMessageType('DceStageAward', (_message.Message,), dict(
  DESCRIPTOR = _DCESTAGEAWARD,
  __module__ = 'DceStageAward_pb2'
  # @@protoc_insertion_point(class_scope:DceStageAward)
  ))
_sym_db.RegisterMessage(DceStageAward)


# @@protoc_insertion_point(module_scope)
