# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceTownPatrolOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceTownPatrolOpt.proto',
  package='',
  serialized_pb=_b('\n\x16\x44\x63\x65TownPatrolOpt.proto\"?\n\x10\x44\x63\x65TownPatrolOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\x05\x12\x0e\n\x06hoepos\x18\x03 \x03(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCETOWNPATROLOPT = _descriptor.Descriptor(
  name='DceTownPatrolOpt',
  full_name='DceTownPatrolOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DceTownPatrolOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DceTownPatrolOpt.param', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hoepos', full_name='DceTownPatrolOpt.hoepos', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['DceTownPatrolOpt'] = _DCETOWNPATROLOPT

DceTownPatrolOpt = _reflection.GeneratedProtocolMessageType('DceTownPatrolOpt', (_message.Message,), dict(
  DESCRIPTOR = _DCETOWNPATROLOPT,
  __module__ = 'DceTownPatrolOpt_pb2'
  # @@protoc_insertion_point(class_scope:DceTownPatrolOpt)
  ))
_sym_db.RegisterMessage(DceTownPatrolOpt)


# @@protoc_insertion_point(module_scope)
