# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceUserInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceUserInfo.proto',
  package='',
  serialized_pb=_b('\n\x11\x44\x63\x65UserInfo.proto\"\r\n\x0b\x44\x63\x65UserInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEUSERINFO = _descriptor.Descriptor(
  name='DceUserInfo',
  full_name='DceUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=34,
)

DESCRIPTOR.message_types_by_name['DceUserInfo'] = _DCEUSERINFO

DceUserInfo = _reflection.GeneratedProtocolMessageType('DceUserInfo', (_message.Message,), dict(
  DESCRIPTOR = _DCEUSERINFO,
  __module__ = 'DceUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:DceUserInfo)
  ))
_sym_db.RegisterMessage(DceUserInfo)


# @@protoc_insertion_point(module_scope)
