# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DceUseItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DceUseItem.proto',
  package='',
  serialized_pb=_b('\n\x10\x44\x63\x65UseItem.proto\"I\n\nDceUseItem\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\r\n\x05param\x18\x03 \x01(\x05\x12\x0f\n\x07msgType\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DCEUSEITEM = _descriptor.Descriptor(
  name='DceUseItem',
  full_name='DceUseItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='DceUseItem.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='DceUseItem.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DceUseItem.param', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='DceUseItem.msgType', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['DceUseItem'] = _DCEUSEITEM

DceUseItem = _reflection.GeneratedProtocolMessageType('DceUseItem', (_message.Message,), dict(
  DESCRIPTOR = _DCEUSEITEM,
  __module__ = 'DceUseItem_pb2'
  # @@protoc_insertion_point(class_scope:DceUseItem)
  ))
_sym_db.RegisterMessage(DceUseItem)


# @@protoc_insertion_point(module_scope)
