# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseAuthState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseAuthState.proto',
  package='',
  serialized_pb=_b('\n\x12\x44seAuthState.proto\"d\n\x0c\x44seAuthState\x12\x0c\n\x04pass\x18\x01 \x02(\x08\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\x0f\n\x07leftMin\x18\x03 \x02(\x05\x12\x0c\n\x04time\x18\x04 \x02(\x05\x12\x0c\n\x04zone\x18\x05 \x02(\x05\x12\x0b\n\x03uid\x18\x06 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEAUTHSTATE = _descriptor.Descriptor(
  name='DseAuthState',
  full_name='DseAuthState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pass', full_name='DseAuthState.pass', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseAuthState.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftMin', full_name='DseAuthState.leftMin', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='DseAuthState.time', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone', full_name='DseAuthState.zone', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='DseAuthState.uid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['DseAuthState'] = _DSEAUTHSTATE

DseAuthState = _reflection.GeneratedProtocolMessageType('DseAuthState', (_message.Message,), dict(
  DESCRIPTOR = _DSEAUTHSTATE,
  __module__ = 'DseAuthState_pb2'
  # @@protoc_insertion_point(class_scope:DseAuthState)
  ))
_sym_db.RegisterMessage(DseAuthState)


# @@protoc_insertion_point(module_scope)
