# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseArenaOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RankPlayer_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseArenaOpt.proto',
  package='',
  serialized_pb=_b('\n\x11\x44seArenaOpt.proto\x1a\x10RankPlayer.proto\"M\n\x0b\x44seArenaOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03res\x18\x02 \x01(\x05\x12#\n\ntargetlist\x18\x03 \x01(\x0b\x32\x0f.RankPlayerList')
  ,
  dependencies=[RankPlayer_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEARENAOPT = _descriptor.Descriptor(
  name='DseArenaOpt',
  full_name='DseArenaOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseArenaOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DseArenaOpt.res', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetlist', full_name='DseArenaOpt.targetlist', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=116,
)

_DSEARENAOPT.fields_by_name['targetlist'].message_type = RankPlayer_pb2._RANKPLAYERLIST
DESCRIPTOR.message_types_by_name['DseArenaOpt'] = _DSEARENAOPT

DseArenaOpt = _reflection.GeneratedProtocolMessageType('DseArenaOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEARENAOPT,
  __module__ = 'DseArenaOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseArenaOpt)
  ))
_sym_db.RegisterMessage(DseArenaOpt)


# @@protoc_insertion_point(module_scope)
