# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseBattleOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleInfo_pb2
import BattleAction_pb2
import BattleSettle_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseBattleOpt.proto',
  package='',
  serialized_pb=_b('\n\x12\x44seBattleOpt.proto\x1a\x10\x42\x61ttleInfo.proto\x1a\x12\x42\x61ttleAction.proto\x1a\x12\x42\x61ttleSettle.proto\"\xf8\x01\n\x0c\x44seBattleOpt\x12\x10\n\x08opt_type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05param\x18\x03 \x01(\x05\x12\x0b\n\x03res\x18\x04 \x01(\x05\x12\x1d\n\x06\x61\x63tion\x18\x05 \x03(\x0b\x32\r.BattleAction\x12\x0e\n\x06isover\x18\x06 \x01(\x08\x12\x1f\n\nbattleinfo\x18\x07 \x01(\x0b\x32\x0b.BattleInfo\x12\x12\n\nsendclient\x18\x08 \x01(\x08\x12#\n\x0c\x42\x61ttleSettle\x18\t \x01(\x0b\x32\r.BattleSettle\x12\x12\n\ntransparam\x18\n \x01(\x05\x12\x11\n\tsatifycon\x18\x0b \x01(\x08')
  ,
  dependencies=[BattleInfo_pb2.DESCRIPTOR,BattleAction_pb2.DESCRIPTOR,BattleSettle_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEBATTLEOPT = _descriptor.Descriptor(
  name='DseBattleOpt',
  full_name='DseBattleOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opt_type', full_name='DseBattleOpt.opt_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='DseBattleOpt.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DseBattleOpt.param', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DseBattleOpt.res', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='DseBattleOpt.action', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isover', full_name='DseBattleOpt.isover', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battleinfo', full_name='DseBattleOpt.battleinfo', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sendclient', full_name='DseBattleOpt.sendclient', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BattleSettle', full_name='DseBattleOpt.BattleSettle', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transparam', full_name='DseBattleOpt.transparam', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satifycon', full_name='DseBattleOpt.satifycon', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=329,
)

_DSEBATTLEOPT.fields_by_name['action'].message_type = BattleAction_pb2._BATTLEACTION
_DSEBATTLEOPT.fields_by_name['battleinfo'].message_type = BattleInfo_pb2._BATTLEINFO
_DSEBATTLEOPT.fields_by_name['BattleSettle'].message_type = BattleSettle_pb2._BATTLESETTLE
DESCRIPTOR.message_types_by_name['DseBattleOpt'] = _DSEBATTLEOPT

DseBattleOpt = _reflection.GeneratedProtocolMessageType('DseBattleOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEBATTLEOPT,
  __module__ = 'DseBattleOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseBattleOpt)
  ))
_sym_db.RegisterMessage(DseBattleOpt)


# @@protoc_insertion_point(module_scope)
