# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseBattleSweep.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleSettle_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseBattleSweep.proto',
  package='',
  serialized_pb=_b('\n\x14\x44seBattleSweep.proto\x1a\x12\x42\x61ttleSettle.proto\"b\n\x0e\x44seBattleSweep\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x10\n\x08targetID\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12#\n\x0c\x42\x61ttleSettle\x18\x04 \x03(\x0b\x32\r.BattleSettle')
  ,
  dependencies=[BattleSettle_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEBATTLESWEEP = _descriptor.Descriptor(
  name='DseBattleSweep',
  full_name='DseBattleSweep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseBattleSweep.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetID', full_name='DseBattleSweep.targetID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseBattleSweep.type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BattleSettle', full_name='DseBattleSweep.BattleSettle', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=142,
)

_DSEBATTLESWEEP.fields_by_name['BattleSettle'].message_type = BattleSettle_pb2._BATTLESETTLE
DESCRIPTOR.message_types_by_name['DseBattleSweep'] = _DSEBATTLESWEEP

DseBattleSweep = _reflection.GeneratedProtocolMessageType('DseBattleSweep', (_message.Message,), dict(
  DESCRIPTOR = _DSEBATTLESWEEP,
  __module__ = 'DseBattleSweep_pb2'
  # @@protoc_insertion_point(class_scope:DseBattleSweep)
  ))
_sym_db.RegisterMessage(DseBattleSweep)


# @@protoc_insertion_point(module_scope)
