# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseBattleStart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleInfo_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseBattleStart.proto',
  package='',
  serialized_pb=_b('\n\x14\x44seBattleStart.proto\x1a\x10\x42\x61ttleInfo.proto\"S\n\x0e\x44seBattleStart\x12\x10\n\x08targetID\x18\x01 \x01(\t\x12\x1f\n\nbattleinfo\x18\x02 \x01(\x0b\x32\x0b.BattleInfo\x12\x0e\n\x06result\x18\x03 \x01(\x05')
  ,
  dependencies=[BattleInfo_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEBATTLESTART = _descriptor.Descriptor(
  name='DseBattleStart',
  full_name='DseBattleStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetID', full_name='DseBattleStart.targetID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battleinfo', full_name='DseBattleStart.battleinfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='DseBattleStart.result', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=125,
)

_DSEBATTLESTART.fields_by_name['battleinfo'].message_type = BattleInfo_pb2._BATTLEINFO
DESCRIPTOR.message_types_by_name['DseBattleStart'] = _DSEBATTLESTART

DseBattleStart = _reflection.GeneratedProtocolMessageType('DseBattleStart', (_message.Message,), dict(
  DESCRIPTOR = _DSEBATTLESTART,
  __module__ = 'DseBattleStart_pb2'
  # @@protoc_insertion_point(class_scope:DseBattleStart)
  ))
_sym_db.RegisterMessage(DseBattleStart)


# @@protoc_insertion_point(module_scope)
