# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseCombineProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseCombineProto.proto',
  package='',
  serialized_pb=_b('\n\x15\x44seCombineProto.proto\"\x1e\n\x0f\x44seCombineProto\x12\x0b\n\x03res\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSECOMBINEPROTO = _descriptor.Descriptor(
  name='DseCombineProto',
  full_name='DseCombineProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseCombineProto.res', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['DseCombineProto'] = _DSECOMBINEPROTO

DseCombineProto = _reflection.GeneratedProtocolMessageType('DseCombineProto', (_message.Message,), dict(
  DESCRIPTOR = _DSECOMBINEPROTO,
  __module__ = 'DseCombineProto_pb2'
  # @@protoc_insertion_point(class_scope:DseCombineProto)
  ))
_sym_db.RegisterMessage(DseCombineProto)


# @@protoc_insertion_point(module_scope)
