# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseChatMsgAll.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DseChatMsg_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseChatMsgAll.proto',
  package='',
  serialized_pb=_b('\n\x13\x44seChatMsgAll.proto\x1a\x10\x44seChatMsg.proto\"]\n\x10\x42lackContactData\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x10\n\x08viplevel\x18\x04 \x01(\x05\x12\r\n\x05power\x18\x05 \x01(\x05\"a\n\rDseChatMsgAll\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x1c\n\x07\x63hatmsg\x18\x02 \x03(\x0b\x32\x0b.DseChatMsg\x12$\n\tblacklist\x18\x03 \x03(\x0b\x32\x11.BlackContactData')
  ,
  dependencies=[DseChatMsg_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BLACKCONTACTDATA = _descriptor.Descriptor(
  name='BlackContactData',
  full_name='BlackContactData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='BlackContactData.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='BlackContactData.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='BlackContactData.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='viplevel', full_name='BlackContactData.viplevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='BlackContactData.power', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=134,
)


_DSECHATMSGALL = _descriptor.Descriptor(
  name='DseChatMsgAll',
  full_name='DseChatMsgAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseChatMsgAll.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chatmsg', full_name='DseChatMsgAll.chatmsg', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blacklist', full_name='DseChatMsgAll.blacklist', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=233,
)

_DSECHATMSGALL.fields_by_name['chatmsg'].message_type = DseChatMsg_pb2._DSECHATMSG
_DSECHATMSGALL.fields_by_name['blacklist'].message_type = _BLACKCONTACTDATA
DESCRIPTOR.message_types_by_name['BlackContactData'] = _BLACKCONTACTDATA
DESCRIPTOR.message_types_by_name['DseChatMsgAll'] = _DSECHATMSGALL

BlackContactData = _reflection.GeneratedProtocolMessageType('BlackContactData', (_message.Message,), dict(
  DESCRIPTOR = _BLACKCONTACTDATA,
  __module__ = 'DseChatMsgAll_pb2'
  # @@protoc_insertion_point(class_scope:BlackContactData)
  ))
_sym_db.RegisterMessage(BlackContactData)

DseChatMsgAll = _reflection.GeneratedProtocolMessageType('DseChatMsgAll', (_message.Message,), dict(
  DESCRIPTOR = _DSECHATMSGALL,
  __module__ = 'DseChatMsgAll_pb2'
  # @@protoc_insertion_point(class_scope:DseChatMsgAll)
  ))
_sym_db.RegisterMessage(DseChatMsgAll)


# @@protoc_insertion_point(module_scope)
