# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseDailyMissionOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseDailyMissionOpt.proto',
  package='',
  serialized_pb=_b('\n\x18\x44seDailyMissionOpt.proto\x1a\x0fMDropList.proto\"<\n\x0f\x44\x61ilyMissionOne\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05times\x18\x02 \x01(\x05\x12\x0e\n\x06reward\x18\x03 \x01(\x08\"c\n\x10\x44\x61ilyMissionData\x12%\n\x0bmissionlist\x18\x01 \x03(\x0b\x32\x10.DailyMissionOne\x12\x12\n\nactiveness\x18\x02 \x01(\x05\x12\x14\n\x0c\x61\x63tivereward\x18\x03 \x03(\x05\"\x84\x01\n\x12\x44seDailyMissionOpt\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05param\x18\x03 \x01(\x05\x12\x1c\n\x08\x64roplist\x18\x04 \x01(\x0b\x32\n.MDropList\x12&\n\x0bmissiondata\x18\x05 \x01(\x0b\x32\x11.DailyMissionData')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DAILYMISSIONONE = _descriptor.Descriptor(
  name='DailyMissionOne',
  full_name='DailyMissionOne',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DailyMissionOne.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='times', full_name='DailyMissionOne.times', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='DailyMissionOne.reward', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=105,
)


_DAILYMISSIONDATA = _descriptor.Descriptor(
  name='DailyMissionData',
  full_name='DailyMissionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='missionlist', full_name='DailyMissionData.missionlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activeness', full_name='DailyMissionData.activeness', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activereward', full_name='DailyMissionData.activereward', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=206,
)


_DSEDAILYMISSIONOPT = _descriptor.Descriptor(
  name='DseDailyMissionOpt',
  full_name='DseDailyMissionOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseDailyMissionOpt.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseDailyMissionOpt.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DseDailyMissionOpt.param', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='droplist', full_name='DseDailyMissionOpt.droplist', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='missiondata', full_name='DseDailyMissionOpt.missiondata', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=341,
)

_DAILYMISSIONDATA.fields_by_name['missionlist'].message_type = _DAILYMISSIONONE
_DSEDAILYMISSIONOPT.fields_by_name['droplist'].message_type = MDropList_pb2._MDROPLIST
_DSEDAILYMISSIONOPT.fields_by_name['missiondata'].message_type = _DAILYMISSIONDATA
DESCRIPTOR.message_types_by_name['DailyMissionOne'] = _DAILYMISSIONONE
DESCRIPTOR.message_types_by_name['DailyMissionData'] = _DAILYMISSIONDATA
DESCRIPTOR.message_types_by_name['DseDailyMissionOpt'] = _DSEDAILYMISSIONOPT

DailyMissionOne = _reflection.GeneratedProtocolMessageType('DailyMissionOne', (_message.Message,), dict(
  DESCRIPTOR = _DAILYMISSIONONE,
  __module__ = 'DseDailyMissionOpt_pb2'
  # @@protoc_insertion_point(class_scope:DailyMissionOne)
  ))
_sym_db.RegisterMessage(DailyMissionOne)

DailyMissionData = _reflection.GeneratedProtocolMessageType('DailyMissionData', (_message.Message,), dict(
  DESCRIPTOR = _DAILYMISSIONDATA,
  __module__ = 'DseDailyMissionOpt_pb2'
  # @@protoc_insertion_point(class_scope:DailyMissionData)
  ))
_sym_db.RegisterMessage(DailyMissionData)

DseDailyMissionOpt = _reflection.GeneratedProtocolMessageType('DseDailyMissionOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEDAILYMISSIONOPT,
  __module__ = 'DseDailyMissionOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseDailyMissionOpt)
  ))
_sym_db.RegisterMessage(DseDailyMissionOpt)


# @@protoc_insertion_point(module_scope)
