# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseDailyActivityOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseDailyActivityOpt.proto',
  package='',
  serialized_pb=_b('\n\x19\x44seDailyActivityOpt.proto\"*\n\x0cSpiritInvest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"\xa3\x01\n\x11\x44\x61ilyActivityData\x12\x14\n\x0c\x66oodsupplyid\x18\x01 \x01(\x05\x12\x16\n\x0emonthsignindex\x18\x02 \x01(\x05\x12\x16\n\x0emonthsignstate\x18\x03 \x01(\x05\x12\x13\n\x0blevelreward\x18\x04 \x03(\x05\x12\x10\n\x08isinvest\x18\x05 \x01(\x08\x12!\n\ninvestdata\x18\x06 \x03(\x0b\x32\r.SpiritInvest\"n\n\x13\x44seDailyActivityOpt\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05param\x18\x03 \x01(\x05\x12-\n\x11\x64\x61ilyactivitydata\x18\x04 \x01(\x0b\x32\x12.DailyActivityData')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPIRITINVEST = _descriptor.Descriptor(
  name='SpiritInvest',
  full_name='SpiritInvest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SpiritInvest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='SpiritInvest.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=71,
)


_DAILYACTIVITYDATA = _descriptor.Descriptor(
  name='DailyActivityData',
  full_name='DailyActivityData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='foodsupplyid', full_name='DailyActivityData.foodsupplyid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='monthsignindex', full_name='DailyActivityData.monthsignindex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='monthsignstate', full_name='DailyActivityData.monthsignstate', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='levelreward', full_name='DailyActivityData.levelreward', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isinvest', full_name='DailyActivityData.isinvest', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='investdata', full_name='DailyActivityData.investdata', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=237,
)


_DSEDAILYACTIVITYOPT = _descriptor.Descriptor(
  name='DseDailyActivityOpt',
  full_name='DseDailyActivityOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseDailyActivityOpt.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseDailyActivityOpt.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DseDailyActivityOpt.param', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dailyactivitydata', full_name='DseDailyActivityOpt.dailyactivitydata', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=349,
)

_DAILYACTIVITYDATA.fields_by_name['investdata'].message_type = _SPIRITINVEST
_DSEDAILYACTIVITYOPT.fields_by_name['dailyactivitydata'].message_type = _DAILYACTIVITYDATA
DESCRIPTOR.message_types_by_name['SpiritInvest'] = _SPIRITINVEST
DESCRIPTOR.message_types_by_name['DailyActivityData'] = _DAILYACTIVITYDATA
DESCRIPTOR.message_types_by_name['DseDailyActivityOpt'] = _DSEDAILYACTIVITYOPT

SpiritInvest = _reflection.GeneratedProtocolMessageType('SpiritInvest', (_message.Message,), dict(
  DESCRIPTOR = _SPIRITINVEST,
  __module__ = 'DseDailyActivityOpt_pb2'
  # @@protoc_insertion_point(class_scope:SpiritInvest)
  ))
_sym_db.RegisterMessage(SpiritInvest)

DailyActivityData = _reflection.GeneratedProtocolMessageType('DailyActivityData', (_message.Message,), dict(
  DESCRIPTOR = _DAILYACTIVITYDATA,
  __module__ = 'DseDailyActivityOpt_pb2'
  # @@protoc_insertion_point(class_scope:DailyActivityData)
  ))
_sym_db.RegisterMessage(DailyActivityData)

DseDailyActivityOpt = _reflection.GeneratedProtocolMessageType('DseDailyActivityOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEDAILYACTIVITYOPT,
  __module__ = 'DseDailyActivityOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseDailyActivityOpt)
  ))
_sym_db.RegisterMessage(DseDailyActivityOpt)


# @@protoc_insertion_point(module_scope)
