# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseDecreeShopOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ShopUnit_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseDecreeShopOpt.proto',
  package='',
  serialized_pb=_b('\n\x16\x44seDecreeShopOpt.proto\x1a\x0eShopUnit.proto\"q\n\nDecreeShop\x12\x11\n\tfreetimes\x18\x01 \x01(\x05\x12\x17\n\x0flastrefreshtime\x18\x02 \x01(\t\x12\x1a\n\x12remainrefreshtimes\x18\x03 \x01(\x05\x12\x1b\n\x08shoplist\x18\x04 \x03(\x0b\x32\t.ShopUnit\"]\n\x10\x44seDecreeShopOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0b\n\x03res\x18\x03 \x01(\x05\x12\x1f\n\ndecreeshop\x18\x04 \x01(\x0b\x32\x0b.DecreeShop')
  ,
  dependencies=[ShopUnit_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DECREESHOP = _descriptor.Descriptor(
  name='DecreeShop',
  full_name='DecreeShop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='freetimes', full_name='DecreeShop.freetimes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastrefreshtime', full_name='DecreeShop.lastrefreshtime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remainrefreshtimes', full_name='DecreeShop.remainrefreshtimes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shoplist', full_name='DecreeShop.shoplist', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=155,
)


_DSEDECREESHOPOPT = _descriptor.Descriptor(
  name='DseDecreeShopOpt',
  full_name='DseDecreeShopOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseDecreeShopOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='DseDecreeShopOpt.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DseDecreeShopOpt.res', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decreeshop', full_name='DseDecreeShopOpt.decreeshop', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=250,
)

_DECREESHOP.fields_by_name['shoplist'].message_type = ShopUnit_pb2._SHOPUNIT
_DSEDECREESHOPOPT.fields_by_name['decreeshop'].message_type = _DECREESHOP
DESCRIPTOR.message_types_by_name['DecreeShop'] = _DECREESHOP
DESCRIPTOR.message_types_by_name['DseDecreeShopOpt'] = _DSEDECREESHOPOPT

DecreeShop = _reflection.GeneratedProtocolMessageType('DecreeShop', (_message.Message,), dict(
  DESCRIPTOR = _DECREESHOP,
  __module__ = 'DseDecreeShopOpt_pb2'
  # @@protoc_insertion_point(class_scope:DecreeShop)
  ))
_sym_db.RegisterMessage(DecreeShop)

DseDecreeShopOpt = _reflection.GeneratedProtocolMessageType('DseDecreeShopOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEDECREESHOPOPT,
  __module__ = 'DseDecreeShopOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseDecreeShopOpt)
  ))
_sym_db.RegisterMessage(DseDecreeShopOpt)


# @@protoc_insertion_point(module_scope)
