# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseDugeonOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseDugeonOpt.proto',
  package='',
  serialized_pb=_b('\n\x12\x44seDugeonOpt.proto\"X\n\nDugeonItem\x12\x0f\n\x07process\x18\x01 \x01(\x05\x12\x13\n\x0bremaintimes\x18\x02 \x01(\x05\x12\x12\n\ntotaltimes\x18\x03 \x01(\x05\x12\x10\n\x08stageids\x18\x04 \x03(\x05\"P\n\nDugeonData\x12\x1e\n\talldugeon\x18\x01 \x03(\x0b\x32\x0b.DugeonItem\x12\x0f\n\x07\x62uycost\x18\x02 \x01(\x05\x12\x11\n\tremainbuy\x18\x03 \x01(\x05\"J\n\x0c\x44seDugeonOpt\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x1f\n\ndugeondata\x18\x03 \x01(\x0b\x32\x0b.DugeonData')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DUGEONITEM = _descriptor.Descriptor(
  name='DugeonItem',
  full_name='DugeonItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process', full_name='DugeonItem.process', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remaintimes', full_name='DugeonItem.remaintimes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totaltimes', full_name='DugeonItem.totaltimes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stageids', full_name='DugeonItem.stageids', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=110,
)


_DUGEONDATA = _descriptor.Descriptor(
  name='DugeonData',
  full_name='DugeonData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alldugeon', full_name='DugeonData.alldugeon', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buycost', full_name='DugeonData.buycost', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remainbuy', full_name='DugeonData.remainbuy', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=192,
)


_DSEDUGEONOPT = _descriptor.Descriptor(
  name='DseDugeonOpt',
  full_name='DseDugeonOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseDugeonOpt.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseDugeonOpt.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dugeondata', full_name='DseDugeonOpt.dugeondata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=268,
)

_DUGEONDATA.fields_by_name['alldugeon'].message_type = _DUGEONITEM
_DSEDUGEONOPT.fields_by_name['dugeondata'].message_type = _DUGEONDATA
DESCRIPTOR.message_types_by_name['DugeonItem'] = _DUGEONITEM
DESCRIPTOR.message_types_by_name['DugeonData'] = _DUGEONDATA
DESCRIPTOR.message_types_by_name['DseDugeonOpt'] = _DSEDUGEONOPT

DugeonItem = _reflection.GeneratedProtocolMessageType('DugeonItem', (_message.Message,), dict(
  DESCRIPTOR = _DUGEONITEM,
  __module__ = 'DseDugeonOpt_pb2'
  # @@protoc_insertion_point(class_scope:DugeonItem)
  ))
_sym_db.RegisterMessage(DugeonItem)

DugeonData = _reflection.GeneratedProtocolMessageType('DugeonData', (_message.Message,), dict(
  DESCRIPTOR = _DUGEONDATA,
  __module__ = 'DseDugeonOpt_pb2'
  # @@protoc_insertion_point(class_scope:DugeonData)
  ))
_sym_db.RegisterMessage(DugeonData)

DseDugeonOpt = _reflection.GeneratedProtocolMessageType('DseDugeonOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEDUGEONOPT,
  __module__ = 'DseDugeonOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseDugeonOpt)
  ))
_sym_db.RegisterMessage(DseDugeonOpt)


# @@protoc_insertion_point(module_scope)
