# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseDailyOlineAwardData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseDailyOlineAwardData.proto',
  package='',
  serialized_pb=_b('\n\x1c\x44seDailyOlineAwardData.proto\"c\n\x16\x44seDailyOlineAwardData\x12\x12\n\nonlinetime\x18\x01 \x01(\t\x12\r\n\x05times\x18\x02 \x01(\x05\x12\x12\n\nawardboxid\x18\x03 \x01(\x05\x12\x12\n\nluckytimes\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEDAILYOLINEAWARDDATA = _descriptor.Descriptor(
  name='DseDailyOlineAwardData',
  full_name='DseDailyOlineAwardData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='onlinetime', full_name='DseDailyOlineAwardData.onlinetime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='times', full_name='DseDailyOlineAwardData.times', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='awardboxid', full_name='DseDailyOlineAwardData.awardboxid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='luckytimes', full_name='DseDailyOlineAwardData.luckytimes', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['DseDailyOlineAwardData'] = _DSEDAILYOLINEAWARDDATA

DseDailyOlineAwardData = _reflection.GeneratedProtocolMessageType('DseDailyOlineAwardData', (_message.Message,), dict(
  DESCRIPTOR = _DSEDAILYOLINEAWARDDATA,
  __module__ = 'DseDailyOlineAwardData_pb2'
  # @@protoc_insertion_point(class_scope:DseDailyOlineAwardData)
  ))
_sym_db.RegisterMessage(DseDailyOlineAwardData)


# @@protoc_insertion_point(module_scope)
