# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseEquipmentEnhance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseEquipmentEnhance.proto',
  package='',
  serialized_pb=_b('\n\x19\x44seEquipmentEnhance.proto\"0\n\x13\x44seEquipmentEnhance\x12\x0b\n\x03oid\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEEQUIPMENTENHANCE = _descriptor.Descriptor(
  name='DseEquipmentEnhance',
  full_name='DseEquipmentEnhance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oid', full_name='DseEquipmentEnhance.oid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='DseEquipmentEnhance.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['DseEquipmentEnhance'] = _DSEEQUIPMENTENHANCE

DseEquipmentEnhance = _reflection.GeneratedProtocolMessageType('DseEquipmentEnhance', (_message.Message,), dict(
  DESCRIPTOR = _DSEEQUIPMENTENHANCE,
  __module__ = 'DseEquipmentEnhance_pb2'
  # @@protoc_insertion_point(class_scope:DseEquipmentEnhance)
  ))
_sym_db.RegisterMessage(DseEquipmentEnhance)


# @@protoc_insertion_point(module_scope)
