# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseFormationInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EquipmentInfoLite_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseFormationInfo.proto',
  package='',
  serialized_pb=_b('\n\x16\x44seFormationInfo.proto\x1a\x17\x45quipmentInfoLite.proto\"M\n\rSingleSoldier\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x0b\n\x03tid\x18\x02 \x01(\x05\x12\"\n\x06\x65quips\x18\x03 \x03(\x0b\x32\x12.EquipmentInfoLite\"F\n\x10\x44seFormationInfo\x12\x1d\n\x05\x66orms\x18\x01 \x03(\x0b\x32\x0e.SingleSoldier\x12\x13\n\x0b\x63\x61ptain_pos\x18\x02 \x01(\x05')
  ,
  dependencies=[EquipmentInfoLite_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SINGLESOLDIER = _descriptor.Descriptor(
  name='SingleSoldier',
  full_name='SingleSoldier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='SingleSoldier.pos', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tid', full_name='SingleSoldier.tid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='equips', full_name='SingleSoldier.equips', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=128,
)


_DSEFORMATIONINFO = _descriptor.Descriptor(
  name='DseFormationInfo',
  full_name='DseFormationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forms', full_name='DseFormationInfo.forms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='captain_pos', full_name='DseFormationInfo.captain_pos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=200,
)

_SINGLESOLDIER.fields_by_name['equips'].message_type = EquipmentInfoLite_pb2._EQUIPMENTINFOLITE
_DSEFORMATIONINFO.fields_by_name['forms'].message_type = _SINGLESOLDIER
DESCRIPTOR.message_types_by_name['SingleSoldier'] = _SINGLESOLDIER
DESCRIPTOR.message_types_by_name['DseFormationInfo'] = _DSEFORMATIONINFO

SingleSoldier = _reflection.GeneratedProtocolMessageType('SingleSoldier', (_message.Message,), dict(
  DESCRIPTOR = _SINGLESOLDIER,
  __module__ = 'DseFormationInfo_pb2'
  # @@protoc_insertion_point(class_scope:SingleSoldier)
  ))
_sym_db.RegisterMessage(SingleSoldier)

DseFormationInfo = _reflection.GeneratedProtocolMessageType('DseFormationInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSEFORMATIONINFO,
  __module__ = 'DseFormationInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseFormationInfo)
  ))
_sym_db.RegisterMessage(DseFormationInfo)


# @@protoc_insertion_point(module_scope)
