# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseGuildData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseGuildData.proto',
  package='',
  serialized_pb=_b('\n\x12\x44seGuildData.proto\"g\n\x0fGuildMemberData\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05grade\x18\x02 \x01(\x05\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x0c\n\x04head\x18\x04 \x01(\x05\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\r\n\x05power\x18\x06 \x01(\x05\"\xfc\x01\n\x0c\x44seGuildData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x12\n\ncontribute\x18\x04 \x01(\x05\x12\x0e\n\x06\x64\x65\x63lar\x18\x05 \x01(\t\x12\x0e\n\x06notify\x18\x06 \x01(\t\x12\r\n\x05\x62\x61\x64ge\x18\x07 \x01(\x05\x12\x12\n\napplylevel\x18\x08 \x01(\x05\x12\x14\n\x0c\x61utoapproval\x18\t \x01(\x08\x12$\n\nmemberlist\x18\n \x03(\x0b\x32\x10.GuildMemberData\x12#\n\tapplylist\x18\x0b \x03(\x0b\x32\x10.GuildMemberData\x12\x0b\n\x03way\x18\x0c \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GUILDMEMBERDATA = _descriptor.Descriptor(
  name='GuildMemberData',
  full_name='GuildMemberData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='GuildMemberData.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='GuildMemberData.grade', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='GuildMemberData.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head', full_name='GuildMemberData.head', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='GuildMemberData.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='GuildMemberData.power', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=125,
)


_DSEGUILDDATA = _descriptor.Descriptor(
  name='DseGuildData',
  full_name='DseGuildData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DseGuildData.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='DseGuildData.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='DseGuildData.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contribute', full_name='DseGuildData.contribute', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='declar', full_name='DseGuildData.declar', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify', full_name='DseGuildData.notify', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='badge', full_name='DseGuildData.badge', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applylevel', full_name='DseGuildData.applylevel', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='autoapproval', full_name='DseGuildData.autoapproval', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memberlist', full_name='DseGuildData.memberlist', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applylist', full_name='DseGuildData.applylist', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='way', full_name='DseGuildData.way', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=380,
)

_DSEGUILDDATA.fields_by_name['memberlist'].message_type = _GUILDMEMBERDATA
_DSEGUILDDATA.fields_by_name['applylist'].message_type = _GUILDMEMBERDATA
DESCRIPTOR.message_types_by_name['GuildMemberData'] = _GUILDMEMBERDATA
DESCRIPTOR.message_types_by_name['DseGuildData'] = _DSEGUILDDATA

GuildMemberData = _reflection.GeneratedProtocolMessageType('GuildMemberData', (_message.Message,), dict(
  DESCRIPTOR = _GUILDMEMBERDATA,
  __module__ = 'DseGuildData_pb2'
  # @@protoc_insertion_point(class_scope:GuildMemberData)
  ))
_sym_db.RegisterMessage(GuildMemberData)

DseGuildData = _reflection.GeneratedProtocolMessageType('DseGuildData', (_message.Message,), dict(
  DESCRIPTOR = _DSEGUILDDATA,
  __module__ = 'DseGuildData_pb2'
  # @@protoc_insertion_point(class_scope:DseGuildData)
  ))
_sym_db.RegisterMessage(DseGuildData)


# @@protoc_insertion_point(module_scope)
