# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseGuildKickMember.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseGuildKickMember.proto',
  package='',
  serialized_pb=_b('\n\x18\x44seGuildKickMember.proto\"!\n\x12\x44seGuildKickMember\x12\x0b\n\x03res\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEGUILDKICKMEMBER = _descriptor.Descriptor(
  name='DseGuildKickMember',
  full_name='DseGuildKickMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseGuildKickMember.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['DseGuildKickMember'] = _DSEGUILDKICKMEMBER

DseGuildKickMember = _reflection.GeneratedProtocolMessageType('DseGuildKickMember', (_message.Message,), dict(
  DESCRIPTOR = _DSEGUILDKICKMEMBER,
  __module__ = 'DseGuildKickMember_pb2'
  # @@protoc_insertion_point(class_scope:DseGuildKickMember)
  ))
_sym_db.RegisterMessage(DseGuildKickMember)


# @@protoc_insertion_point(module_scope)
