# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseGuildCreate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseGuildCreate.proto',
  package='',
  serialized_pb=_b('\n\x14\x44seGuildCreate.proto\"\x1d\n\x0e\x44seGuildCreate\x12\x0b\n\x03res\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEGUILDCREATE = _descriptor.Descriptor(
  name='DseGuildCreate',
  full_name='DseGuildCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseGuildCreate.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['DseGuildCreate'] = _DSEGUILDCREATE

DseGuildCreate = _reflection.GeneratedProtocolMessageType('DseGuildCreate', (_message.Message,), dict(
  DESCRIPTOR = _DSEGUILDCREATE,
  __module__ = 'DseGuildCreate_pb2'
  # @@protoc_insertion_point(class_scope:DseGuildCreate)
  ))
_sym_db.RegisterMessage(DseGuildCreate)


# @@protoc_insertion_point(module_scope)
