# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseGuildChangeApplyRule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseGuildChangeApplyRule.proto',
  package='',
  serialized_pb=_b('\n\x1d\x44seGuildChangeApplyRule.proto\"C\n\x17\x44seGuildChangeApplyRule\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05param\x18\x03 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEGUILDCHANGEAPPLYRULE = _descriptor.Descriptor(
  name='DseGuildChangeApplyRule',
  full_name='DseGuildChangeApplyRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseGuildChangeApplyRule.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseGuildChangeApplyRule.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DseGuildChangeApplyRule.param', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['DseGuildChangeApplyRule'] = _DSEGUILDCHANGEAPPLYRULE

DseGuildChangeApplyRule = _reflection.GeneratedProtocolMessageType('DseGuildChangeApplyRule', (_message.Message,), dict(
  DESCRIPTOR = _DSEGUILDCHANGEAPPLYRULE,
  __module__ = 'DseGuildChangeApplyRule_pb2'
  # @@protoc_insertion_point(class_scope:DseGuildChangeApplyRule)
  ))
_sym_db.RegisterMessage(DseGuildChangeApplyRule)


# @@protoc_insertion_point(module_scope)
