# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseGuildApplyJoin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseGuildApplyJoin.proto',
  package='',
  serialized_pb=_b('\n\x17\x44seGuildApplyJoin.proto\" \n\x11\x44seGuildApplyJoin\x12\x0b\n\x03res\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEGUILDAPPLYJOIN = _descriptor.Descriptor(
  name='DseGuildApplyJoin',
  full_name='DseGuildApplyJoin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseGuildApplyJoin.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['DseGuildApplyJoin'] = _DSEGUILDAPPLYJOIN

DseGuildApplyJoin = _reflection.GeneratedProtocolMessageType('DseGuildApplyJoin', (_message.Message,), dict(
  DESCRIPTOR = _DSEGUILDAPPLYJOIN,
  __module__ = 'DseGuildApplyJoin_pb2'
  # @@protoc_insertion_point(class_scope:DseGuildApplyJoin)
  ))
_sym_db.RegisterMessage(DseGuildApplyJoin)


# @@protoc_insertion_point(module_scope)
