# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseItemChange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseItemChange.proto',
  package='',
  serialized_pb=_b('\n\x13\x44seItemChange.proto\x1a\x0fMDropList.proto\"J\n\rDseItemChange\x12\x18\n\x04list\x18\x01 \x01(\x0b\x32\n.MDropList\x12\x1f\n\x06source\x18\x02 \x01(\x0e\x32\x0f.ItemSourceType*\x99\x01\n\x0eItemSourceType\x12\x16\n\x12ITEM_SOURCE_NORMAL\x10\x00\x12\x1d\n\x19ITEM_SOURCE_TREASURE_CASE\x10\x01\x12\x14\n\x10ITEM_SOURCE_GIFT\x10\x02\x12\x1f\n\x1bITEM_SOURCE_MULTI_DROP_CASE\x10\x03\x12\x19\n\x15ITEM_SOURCE_PICK_GIFT\x10\x04')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ITEMSOURCETYPE = _descriptor.EnumDescriptor(
  name='ItemSourceType',
  full_name='ItemSourceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ITEM_SOURCE_NORMAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_SOURCE_TREASURE_CASE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_SOURCE_GIFT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_SOURCE_MULTI_DROP_CASE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_SOURCE_PICK_GIFT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=117,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_ITEMSOURCETYPE)

ItemSourceType = enum_type_wrapper.EnumTypeWrapper(_ITEMSOURCETYPE)
ITEM_SOURCE_NORMAL = 0
ITEM_SOURCE_TREASURE_CASE = 1
ITEM_SOURCE_GIFT = 2
ITEM_SOURCE_MULTI_DROP_CASE = 3
ITEM_SOURCE_PICK_GIFT = 4



_DSEITEMCHANGE = _descriptor.Descriptor(
  name='DseItemChange',
  full_name='DseItemChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='DseItemChange.list', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='DseItemChange.source', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=114,
)

_DSEITEMCHANGE.fields_by_name['list'].message_type = MDropList_pb2._MDROPLIST
_DSEITEMCHANGE.fields_by_name['source'].enum_type = _ITEMSOURCETYPE
DESCRIPTOR.message_types_by_name['DseItemChange'] = _DSEITEMCHANGE
DESCRIPTOR.enum_types_by_name['ItemSourceType'] = _ITEMSOURCETYPE

DseItemChange = _reflection.GeneratedProtocolMessageType('DseItemChange', (_message.Message,), dict(
  DESCRIPTOR = _DSEITEMCHANGE,
  __module__ = 'DseItemChange_pb2'
  # @@protoc_insertion_point(class_scope:DseItemChange)
  ))
_sym_db.RegisterMessage(DseItemChange)


# @@protoc_insertion_point(module_scope)
