# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseInstituteOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseInstituteOpt.proto',
  package='',
  serialized_pb=_b('\n\x15\x44seInstituteOpt.proto\"*\n\rInstituteItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\"6\n\rInstituteList\x12%\n\rinstitutelist\x18\x01 \x03(\x0b\x32\x0e.InstituteItem\"o\n\rInstituteData\x12$\n\x0c\x61llinstitute\x18\x01 \x03(\x0b\x32\x0e.InstituteList\x12\x13\n\x0binstituteid\x18\x02 \x01(\x05\x12\x12\n\nfinishtime\x18\x03 \x01(\t\x12\x0f\n\x07\x66reesec\x18\x04 \x01(\x05\"d\n\x0f\x44seInstituteOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x13\n\x0binstituteid\x18\x02 \x01(\x05\x12!\n\tinstitute\x18\x03 \x01(\x0b\x32\x0e.InstituteData\x12\x0b\n\x03res\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INSTITUTEITEM = _descriptor.Descriptor(
  name='InstituteItem',
  full_name='InstituteItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='InstituteItem.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='InstituteItem.level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=67,
)


_INSTITUTELIST = _descriptor.Descriptor(
  name='InstituteList',
  full_name='InstituteList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='institutelist', full_name='InstituteList.institutelist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=123,
)


_INSTITUTEDATA = _descriptor.Descriptor(
  name='InstituteData',
  full_name='InstituteData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allinstitute', full_name='InstituteData.allinstitute', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instituteid', full_name='InstituteData.instituteid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finishtime', full_name='InstituteData.finishtime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='freesec', full_name='InstituteData.freesec', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=236,
)


_DSEINSTITUTEOPT = _descriptor.Descriptor(
  name='DseInstituteOpt',
  full_name='DseInstituteOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseInstituteOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instituteid', full_name='DseInstituteOpt.instituteid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='institute', full_name='DseInstituteOpt.institute', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DseInstituteOpt.res', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=338,
)

_INSTITUTELIST.fields_by_name['institutelist'].message_type = _INSTITUTEITEM
_INSTITUTEDATA.fields_by_name['allinstitute'].message_type = _INSTITUTELIST
_DSEINSTITUTEOPT.fields_by_name['institute'].message_type = _INSTITUTEDATA
DESCRIPTOR.message_types_by_name['InstituteItem'] = _INSTITUTEITEM
DESCRIPTOR.message_types_by_name['InstituteList'] = _INSTITUTELIST
DESCRIPTOR.message_types_by_name['InstituteData'] = _INSTITUTEDATA
DESCRIPTOR.message_types_by_name['DseInstituteOpt'] = _DSEINSTITUTEOPT

InstituteItem = _reflection.GeneratedProtocolMessageType('InstituteItem', (_message.Message,), dict(
  DESCRIPTOR = _INSTITUTEITEM,
  __module__ = 'DseInstituteOpt_pb2'
  # @@protoc_insertion_point(class_scope:InstituteItem)
  ))
_sym_db.RegisterMessage(InstituteItem)

InstituteList = _reflection.GeneratedProtocolMessageType('InstituteList', (_message.Message,), dict(
  DESCRIPTOR = _INSTITUTELIST,
  __module__ = 'DseInstituteOpt_pb2'
  # @@protoc_insertion_point(class_scope:InstituteList)
  ))
_sym_db.RegisterMessage(InstituteList)

InstituteData = _reflection.GeneratedProtocolMessageType('InstituteData', (_message.Message,), dict(
  DESCRIPTOR = _INSTITUTEDATA,
  __module__ = 'DseInstituteOpt_pb2'
  # @@protoc_insertion_point(class_scope:InstituteData)
  ))
_sym_db.RegisterMessage(InstituteData)

DseInstituteOpt = _reflection.GeneratedProtocolMessageType('DseInstituteOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEINSTITUTEOPT,
  __module__ = 'DseInstituteOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseInstituteOpt)
  ))
_sym_db.RegisterMessage(DseInstituteOpt)


# @@protoc_insertion_point(module_scope)
