# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseMailOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseMailOpt.proto',
  package='',
  serialized_pb=_b('\n\x10\x44seMailOpt.proto\x1a\x0fMDropList.proto\"(\n\tParamUnit\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\t\"\xbf\x01\n\x08MailData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncreatetime\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0b\n\x03uid\x18\x06 \x01(\t\x12\x1d\n\tparamlist\x18\x07 \x03(\x0b\x32\n.ParamUnit\x12\x1a\n\x06reward\x18\x08 \x01(\x0b\x32\n.MDropList\x12\r\n\x05isget\x18\t \x01(\x08\x12\x0e\n\x06isread\x18\n \x01(\x08\"\x84\x01\n\nDseMailOpt\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x10\n\x08mailtype\x18\x03 \x01(\x05\x12\x1b\n\x08maillist\x18\x04 \x03(\x0b\x32\t.MailData\x12\x11\n\tnewcounts\x18\x05 \x03(\x05\x12\x19\n\x05\x64rops\x18\x06 \x01(\x0b\x32\n.MDropList')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARAMUNIT = _descriptor.Descriptor(
  name='ParamUnit',
  full_name='ParamUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ParamUnit.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='ParamUnit.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=77,
)


_MAILDATA = _descriptor.Descriptor(
  name='MailData',
  full_name='MailData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MailData.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createtime', full_name='MailData.createtime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='MailData.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='MailData.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='MailData.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='MailData.uid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramlist', full_name='MailData.paramlist', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='MailData.reward', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isget', full_name='MailData.isget', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isread', full_name='MailData.isread', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=271,
)


_DSEMAILOPT = _descriptor.Descriptor(
  name='DseMailOpt',
  full_name='DseMailOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseMailOpt.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseMailOpt.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mailtype', full_name='DseMailOpt.mailtype', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maillist', full_name='DseMailOpt.maillist', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newcounts', full_name='DseMailOpt.newcounts', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drops', full_name='DseMailOpt.drops', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=406,
)

_MAILDATA.fields_by_name['paramlist'].message_type = _PARAMUNIT
_MAILDATA.fields_by_name['reward'].message_type = MDropList_pb2._MDROPLIST
_DSEMAILOPT.fields_by_name['maillist'].message_type = _MAILDATA
_DSEMAILOPT.fields_by_name['drops'].message_type = MDropList_pb2._MDROPLIST
DESCRIPTOR.message_types_by_name['ParamUnit'] = _PARAMUNIT
DESCRIPTOR.message_types_by_name['MailData'] = _MAILDATA
DESCRIPTOR.message_types_by_name['DseMailOpt'] = _DSEMAILOPT

ParamUnit = _reflection.GeneratedProtocolMessageType('ParamUnit', (_message.Message,), dict(
  DESCRIPTOR = _PARAMUNIT,
  __module__ = 'DseMailOpt_pb2'
  # @@protoc_insertion_point(class_scope:ParamUnit)
  ))
_sym_db.RegisterMessage(ParamUnit)

MailData = _reflection.GeneratedProtocolMessageType('MailData', (_message.Message,), dict(
  DESCRIPTOR = _MAILDATA,
  __module__ = 'DseMailOpt_pb2'
  # @@protoc_insertion_point(class_scope:MailData)
  ))
_sym_db.RegisterMessage(MailData)

DseMailOpt = _reflection.GeneratedProtocolMessageType('DseMailOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSEMAILOPT,
  __module__ = 'DseMailOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseMailOpt)
  ))
_sym_db.RegisterMessage(DseMailOpt)


# @@protoc_insertion_point(module_scope)
