# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseQueryUserInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DseSingleSpiritInfo_pb2
import EquipmentInfo_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseQueryUserInfo.proto',
  package='',
  serialized_pb=_b('\n\x16\x44seQueryUserInfo.proto\x1a\x19\x44seSingleSpiritInfo.proto\x1a\x13\x45quipmentInfo.proto\"f\n\x13\x44\x65tailSingleSoldier\x12(\n\nspiritinfo\x18\x01 \x01(\x0b\x32\x14.DseSingleSpiritInfo\x12%\n\requipmentlist\x18\x02 \x03(\x0b\x32\x0e.EquipmentInfo\"\xc9\x01\n\x10\x44seQueryUserInfo\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x10\n\x08vipLevel\x18\x05 \x01(\x05\x12\x0c\n\x04head\x18\x06 \x01(\x05\x12\r\n\x05power\x18\x07 \x01(\x05\x12\x11\n\tguildname\x18\x08 \x01(\t\x12\x12\n\nusedsuitid\x18\t \x01(\x05\x12(\n\nspiritlist\x18\n \x03(\x0b\x32\x14.DetailSingleSoldier')
  ,
  dependencies=[DseSingleSpiritInfo_pb2.DESCRIPTOR,EquipmentInfo_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DETAILSINGLESOLDIER = _descriptor.Descriptor(
  name='DetailSingleSoldier',
  full_name='DetailSingleSoldier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spiritinfo', full_name='DetailSingleSoldier.spiritinfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='equipmentlist', full_name='DetailSingleSoldier.equipmentlist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=176,
)


_DSEQUERYUSERINFO = _descriptor.Descriptor(
  name='DseQueryUserInfo',
  full_name='DseQueryUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseQueryUserInfo.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='DseQueryUserInfo.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='DseQueryUserInfo.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='DseQueryUserInfo.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vipLevel', full_name='DseQueryUserInfo.vipLevel', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head', full_name='DseQueryUserInfo.head', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='DseQueryUserInfo.power', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guildname', full_name='DseQueryUserInfo.guildname', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usedsuitid', full_name='DseQueryUserInfo.usedsuitid', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spiritlist', full_name='DseQueryUserInfo.spiritlist', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=380,
)

_DETAILSINGLESOLDIER.fields_by_name['spiritinfo'].message_type = DseSingleSpiritInfo_pb2._DSESINGLESPIRITINFO
_DETAILSINGLESOLDIER.fields_by_name['equipmentlist'].message_type = EquipmentInfo_pb2._EQUIPMENTINFO
_DSEQUERYUSERINFO.fields_by_name['spiritlist'].message_type = _DETAILSINGLESOLDIER
DESCRIPTOR.message_types_by_name['DetailSingleSoldier'] = _DETAILSINGLESOLDIER
DESCRIPTOR.message_types_by_name['DseQueryUserInfo'] = _DSEQUERYUSERINFO

DetailSingleSoldier = _reflection.GeneratedProtocolMessageType('DetailSingleSoldier', (_message.Message,), dict(
  DESCRIPTOR = _DETAILSINGLESOLDIER,
  __module__ = 'DseQueryUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:DetailSingleSoldier)
  ))
_sym_db.RegisterMessage(DetailSingleSoldier)

DseQueryUserInfo = _reflection.GeneratedProtocolMessageType('DseQueryUserInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSEQUERYUSERINFO,
  __module__ = 'DseQueryUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseQueryUserInfo)
  ))
_sym_db.RegisterMessage(DseQueryUserInfo)


# @@protoc_insertion_point(module_scope)
