# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseResetLeaderResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseResetLeaderResult.proto',
  package='',
  serialized_pb=_b('\n\x1a\x44seResetLeaderResult.proto\"&\n\x14\x44seResetLeaderResult\x12\x0e\n\x06result\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSERESETLEADERRESULT = _descriptor.Descriptor(
  name='DseResetLeaderResult',
  full_name='DseResetLeaderResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='DseResetLeaderResult.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['DseResetLeaderResult'] = _DSERESETLEADERRESULT

DseResetLeaderResult = _reflection.GeneratedProtocolMessageType('DseResetLeaderResult', (_message.Message,), dict(
  DESCRIPTOR = _DSERESETLEADERRESULT,
  __module__ = 'DseResetLeaderResult_pb2'
  # @@protoc_insertion_point(class_scope:DseResetLeaderResult)
  ))
_sym_db.RegisterMessage(DseResetLeaderResult)


# @@protoc_insertion_point(module_scope)
