# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseReforgeSpirit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseReforgeSpirit.proto',
  package='',
  serialized_pb=_b('\n\x16\x44seReforgeSpirit.proto\x1a\x0fMDropList.proto\"W\n\x10\x44seReforgeSpirit\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x12\x0b\n\x03tid\x18\x02 \x03(\x05\x12\x18\n\x04list\x18\x03 \x01(\x0b\x32\n.MDropList\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEREFORGESPIRIT = _descriptor.Descriptor(
  name='DseReforgeSpirit',
  full_name='DseReforgeSpirit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='DseReforgeSpirit.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tid', full_name='DseReforgeSpirit.tid', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list', full_name='DseReforgeSpirit.list', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='DseReforgeSpirit.code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=130,
)

_DSEREFORGESPIRIT.fields_by_name['list'].message_type = MDropList_pb2._MDROPLIST
DESCRIPTOR.message_types_by_name['DseReforgeSpirit'] = _DSEREFORGESPIRIT

DseReforgeSpirit = _reflection.GeneratedProtocolMessageType('DseReforgeSpirit', (_message.Message,), dict(
  DESCRIPTOR = _DSEREFORGESPIRIT,
  __module__ = 'DseReforgeSpirit_pb2'
  # @@protoc_insertion_point(class_scope:DseReforgeSpirit)
  ))
_sym_db.RegisterMessage(DseReforgeSpirit)


# @@protoc_insertion_point(module_scope)
