# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseReformInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseReformInfo.proto',
  package='',
  serialized_pb=_b('\n\x13\x44seReformInfo.proto\"U\n\rDseReformInfo\x12\x10\n\x08spiritid\x18\x01 \x01(\x05\x12\x0f\n\x07\x65ndtime\x18\x02 \x01(\t\x12\x10\n\x08interval\x18\x03 \x01(\x05\x12\x0f\n\x07\x63ostnum\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEREFORMINFO = _descriptor.Descriptor(
  name='DseReformInfo',
  full_name='DseReformInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spiritid', full_name='DseReformInfo.spiritid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endtime', full_name='DseReformInfo.endtime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='DseReformInfo.interval', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='costnum', full_name='DseReformInfo.costnum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['DseReformInfo'] = _DSEREFORMINFO

DseReformInfo = _reflection.GeneratedProtocolMessageType('DseReformInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSEREFORMINFO,
  __module__ = 'DseReformInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseReformInfo)
  ))
_sym_db.RegisterMessage(DseReformInfo)


# @@protoc_insertion_point(module_scope)
