# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseSingleSpiritInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseSingleSpiritInfo.proto',
  package='',
  serialized_pb=_b('\n\x19\x44seSingleSpiritInfo.proto\"\xb2\x02\n\x13\x44seSingleSpiritInfo\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\r\n\x05maxhp\x18\x02 \x01(\x05\x12\x0e\n\x06\x61ttack\x18\x03 \x01(\x05\x12\x0f\n\x07\x64\x65\x66\x65nce\x18\x04 \x01(\x05\x12\r\n\x05speed\x18\x05 \x01(\x05\x12\x11\n\tisCaptain\x18\x06 \x01(\x08\x12\r\n\x05level\x18\x07 \x01(\x05\x12\x10\n\x08reformed\x18\x08 \x01(\x05\x12\x14\n\x0c\x62reakthrough\x18\t \x01(\x05\x12\x10\n\x08upgraded\x18\n \x01(\x05\x12\x10\n\x08\x61wakened\x18\x0b \x01(\x05\x12\x0e\n\x06talent\x18\x0c \x01(\x05\x12\r\n\x05power\x18\r \x01(\x05\x12\x0b\n\x03\x65xp\x18\x0e \x01(\x05\x12\x0c\n\x04skin\x18\x0f \x01(\x05\x12\x15\n\rskin_unlocked\x18\x10 \x03(\x05\x12\x10\n\x08totalexp\x18\x11 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESINGLESPIRITINFO = _descriptor.Descriptor(
  name='DseSingleSpiritInfo',
  full_name='DseSingleSpiritInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='DseSingleSpiritInfo.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxhp', full_name='DseSingleSpiritInfo.maxhp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack', full_name='DseSingleSpiritInfo.attack', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defence', full_name='DseSingleSpiritInfo.defence', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='DseSingleSpiritInfo.speed', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isCaptain', full_name='DseSingleSpiritInfo.isCaptain', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='DseSingleSpiritInfo.level', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reformed', full_name='DseSingleSpiritInfo.reformed', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='breakthrough', full_name='DseSingleSpiritInfo.breakthrough', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upgraded', full_name='DseSingleSpiritInfo.upgraded', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='awakened', full_name='DseSingleSpiritInfo.awakened', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='talent', full_name='DseSingleSpiritInfo.talent', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='DseSingleSpiritInfo.power', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='DseSingleSpiritInfo.exp', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skin', full_name='DseSingleSpiritInfo.skin', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skin_unlocked', full_name='DseSingleSpiritInfo.skin_unlocked', index=15,
      number=16, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalexp', full_name='DseSingleSpiritInfo.totalexp', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=336,
)

DESCRIPTOR.message_types_by_name['DseSingleSpiritInfo'] = _DSESINGLESPIRITINFO

DseSingleSpiritInfo = _reflection.GeneratedProtocolMessageType('DseSingleSpiritInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSESINGLESPIRITINFO,
  __module__ = 'DseSingleSpiritInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseSingleSpiritInfo)
  ))
_sym_db.RegisterMessage(DseSingleSpiritInfo)


# @@protoc_insertion_point(module_scope)
