# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseSummon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseSummon.proto',
  package='',
  serialized_pb=_b('\n\x0f\x44seSummon.proto\x1a\x0fMDropList.proto\"M\n\tDseSummon\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04mode\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\x18\n\x04list\x18\x04 \x01(\x0b\x32\n.MDropList')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESUMMON = _descriptor.Descriptor(
  name='DseSummon',
  full_name='DseSummon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DseSummon.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='DseSummon.mode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='DseSummon.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list', full_name='DseSummon.list', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=113,
)

_DSESUMMON.fields_by_name['list'].message_type = MDropList_pb2._MDROPLIST
DESCRIPTOR.message_types_by_name['DseSummon'] = _DSESUMMON

DseSummon = _reflection.GeneratedProtocolMessageType('DseSummon', (_message.Message,), dict(
  DESCRIPTOR = _DSESUMMON,
  __module__ = 'DseSummon_pb2'
  # @@protoc_insertion_point(class_scope:DseSummon)
  ))
_sym_db.RegisterMessage(DseSummon)


# @@protoc_insertion_point(module_scope)
