# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseStageAward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseStageAward.proto',
  package='',
  serialized_pb=_b('\n\x13\x44seStageAward.proto\"N\n\rDseStageAward\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x11\n\tchapterid\x18\x02 \x01(\x05\x12\x0f\n\x07sceneid\x18\x03 \x01(\x05\x12\x0b\n\x03res\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESTAGEAWARD = _descriptor.Descriptor(
  name='DseStageAward',
  full_name='DseStageAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseStageAward.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chapterid', full_name='DseStageAward.chapterid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sceneid', full_name='DseStageAward.sceneid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DseStageAward.res', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['DseStageAward'] = _DSESTAGEAWARD

DseStageAward = _reflection.GeneratedProtocolMessageType('DseStageAward', (_message.Message,), dict(
  DESCRIPTOR = _DSESTAGEAWARD,
  __module__ = 'DseStageAward_pb2'
  # @@protoc_insertion_point(class_scope:DseStageAward)
  ))
_sym_db.RegisterMessage(DseStageAward)


# @@protoc_insertion_point(module_scope)
