# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseStageReset.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseStageReset.proto',
  package='',
  serialized_pb=_b('\n\x13\x44seStageReset.proto\"\x1c\n\rDseStageReset\x12\x0b\n\x03res\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESTAGERESET = _descriptor.Descriptor(
  name='DseStageReset',
  full_name='DseStageReset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseStageReset.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['DseStageReset'] = _DSESTAGERESET

DseStageReset = _reflection.GeneratedProtocolMessageType('DseStageReset', (_message.Message,), dict(
  DESCRIPTOR = _DSESTAGERESET,
  __module__ = 'DseStageReset_pb2'
  # @@protoc_insertion_point(class_scope:DseStageReset)
  ))
_sym_db.RegisterMessage(DseStageReset)


# @@protoc_insertion_point(module_scope)
