# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseSummonInterface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseSummonInterface.proto',
  package='',
  serialized_pb=_b('\n\x18\x44seSummonInterface.proto\">\n\nSummonPool\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfree_used\x18\x02 \x01(\x05\x12\x11\n\tnext_free\x18\x03 \x01(\t\"0\n\x12\x44seSummonInterface\x12\x1a\n\x05pools\x18\x01 \x03(\x0b\x32\x0b.SummonPool')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SUMMONPOOL = _descriptor.Descriptor(
  name='SummonPool',
  full_name='SummonPool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SummonPool.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='free_used', full_name='SummonPool.free_used', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_free', full_name='SummonPool.next_free', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=90,
)


_DSESUMMONINTERFACE = _descriptor.Descriptor(
  name='DseSummonInterface',
  full_name='DseSummonInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pools', full_name='DseSummonInterface.pools', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=140,
)

_DSESUMMONINTERFACE.fields_by_name['pools'].message_type = _SUMMONPOOL
DESCRIPTOR.message_types_by_name['SummonPool'] = _SUMMONPOOL
DESCRIPTOR.message_types_by_name['DseSummonInterface'] = _DSESUMMONINTERFACE

SummonPool = _reflection.GeneratedProtocolMessageType('SummonPool', (_message.Message,), dict(
  DESCRIPTOR = _SUMMONPOOL,
  __module__ = 'DseSummonInterface_pb2'
  # @@protoc_insertion_point(class_scope:SummonPool)
  ))
_sym_db.RegisterMessage(SummonPool)

DseSummonInterface = _reflection.GeneratedProtocolMessageType('DseSummonInterface', (_message.Message,), dict(
  DESCRIPTOR = _DSESUMMONINTERFACE,
  __module__ = 'DseSummonInterface_pb2'
  # @@protoc_insertion_point(class_scope:DseSummonInterface)
  ))
_sym_db.RegisterMessage(DseSummonInterface)


# @@protoc_insertion_point(module_scope)
