# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseSetRole.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseSetRole.proto',
  package='',
  serialized_pb=_b('\n\x10\x44seSetRole.proto\"9\n\nDseSetRole\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x10\n\x08namelist\x18\x03 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESETROLE = _descriptor.Descriptor(
  name='DseSetRole',
  full_name='DseSetRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='DseSetRole.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DseSetRole.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='namelist', full_name='DseSetRole.namelist', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['DseSetRole'] = _DSESETROLE

DseSetRole = _reflection.GeneratedProtocolMessageType('DseSetRole', (_message.Message,), dict(
  DESCRIPTOR = _DSESETROLE,
  __module__ = 'DseSetRole_pb2'
  # @@protoc_insertion_point(class_scope:DseSetRole)
  ))
_sym_db.RegisterMessage(DseSetRole)


# @@protoc_insertion_point(module_scope)
