# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseStorageList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DceStorageList_pb2
import MItem_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseStorageList.proto',
  package='',
  serialized_pb=_b('\n\x14\x44seStorageList.proto\x1a\x14\x44\x63\x65StorageList.proto\x1a\x0bMItem.proto\"C\n\x0e\x44seStorageList\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.StorageType\x12\x15\n\x05items\x18\x02 \x03(\x0b\x32\x06.MItem')
  ,
  dependencies=[DceStorageList_pb2.DESCRIPTOR,MItem_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESTORAGELIST = _descriptor.Descriptor(
  name='DseStorageList',
  full_name='DseStorageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseStorageList.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='DseStorageList.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=126,
)

_DSESTORAGELIST.fields_by_name['type'].enum_type = DceStorageList_pb2._STORAGETYPE
_DSESTORAGELIST.fields_by_name['items'].message_type = MItem_pb2._MITEM
DESCRIPTOR.message_types_by_name['DseStorageList'] = _DSESTORAGELIST

DseStorageList = _reflection.GeneratedProtocolMessageType('DseStorageList', (_message.Message,), dict(
  DESCRIPTOR = _DSESTORAGELIST,
  __module__ = 'DseStorageList_pb2'
  # @@protoc_insertion_point(class_scope:DseStorageList)
  ))
_sym_db.RegisterMessage(DseStorageList)


# @@protoc_insertion_point(module_scope)
