# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseSwitchFormation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseSwitchFormation.proto',
  package='',
  serialized_pb=_b('\n\x18\x44seSwitchFormation.proto\"\"\n\x12\x44seSwitchFormation\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESWITCHFORMATION = _descriptor.Descriptor(
  name='DseSwitchFormation',
  full_name='DseSwitchFormation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='DseSwitchFormation.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['DseSwitchFormation'] = _DSESWITCHFORMATION

DseSwitchFormation = _reflection.GeneratedProtocolMessageType('DseSwitchFormation', (_message.Message,), dict(
  DESCRIPTOR = _DSESWITCHFORMATION,
  __module__ = 'DseSwitchFormation_pb2'
  # @@protoc_insertion_point(class_scope:DseSwitchFormation)
  ))
_sym_db.RegisterMessage(DseSwitchFormation)


# @@protoc_insertion_point(module_scope)
