# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseSuitList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseSuitList.proto',
  package='',
  serialized_pb=_b('\n\x11\x44seSuitList.proto\"\x1a\n\x08SuitData\x12\x0e\n\x06suidid\x18\x01 \x01(\x05\"*\n\x0b\x44seSuitList\x12\x1b\n\x08suitlist\x18\x01 \x03(\x0b\x32\t.SuitData')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SUITDATA = _descriptor.Descriptor(
  name='SuitData',
  full_name='SuitData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='suidid', full_name='SuitData.suidid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=47,
)


_DSESUITLIST = _descriptor.Descriptor(
  name='DseSuitList',
  full_name='DseSuitList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='suitlist', full_name='DseSuitList.suitlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=91,
)

_DSESUITLIST.fields_by_name['suitlist'].message_type = _SUITDATA
DESCRIPTOR.message_types_by_name['SuitData'] = _SUITDATA
DESCRIPTOR.message_types_by_name['DseSuitList'] = _DSESUITLIST

SuitData = _reflection.GeneratedProtocolMessageType('SuitData', (_message.Message,), dict(
  DESCRIPTOR = _SUITDATA,
  __module__ = 'DseSuitList_pb2'
  # @@protoc_insertion_point(class_scope:SuitData)
  ))
_sym_db.RegisterMessage(SuitData)

DseSuitList = _reflection.GeneratedProtocolMessageType('DseSuitList', (_message.Message,), dict(
  DESCRIPTOR = _DSESUITLIST,
  __module__ = 'DseSuitList_pb2'
  # @@protoc_insertion_point(class_scope:DseSuitList)
  ))
_sym_db.RegisterMessage(DseSuitList)


# @@protoc_insertion_point(module_scope)
