# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseStageExplore.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseStageExplore.proto',
  package='',
  serialized_pb=_b('\n\x15\x44seStageExplore.proto\x1a\x0fMDropList.proto\"\xa0\x01\n\x0b\x45xploreData\x12\x11\n\tstarttime\x18\x01 \x01(\t\x12\x12\n\nmaxendtime\x18\x02 \x01(\t\x12\x11\n\ttotalgold\x18\x03 \x01(\x05\x12\x10\n\x08totalexp\x18\x04 \x01(\x05\x12\x10\n\x08interval\x18\x05 \x01(\x05\x12\x10\n\x08goldonce\x18\x07 \x01(\x05\x12\x0f\n\x07\x65xponce\x18\x08 \x01(\x05\x12\x10\n\x08havedrop\x18\t \x01(\x08\"\x81\x01\n\x0f\x44seStageExplore\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03res\x18\x02 \x01(\x05\x12\x1a\n\x04info\x18\x03 \x01(\x0b\x32\x0c.ExploreData\x12\x0c\n\x04gold\x18\x04 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x05 \x01(\x05\x12\x1c\n\x08\x64roplist\x18\x06 \x01(\x0b\x32\n.MDropList')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXPLOREDATA = _descriptor.Descriptor(
  name='ExploreData',
  full_name='ExploreData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='starttime', full_name='ExploreData.starttime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxendtime', full_name='ExploreData.maxendtime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalgold', full_name='ExploreData.totalgold', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalexp', full_name='ExploreData.totalexp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='ExploreData.interval', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goldonce', full_name='ExploreData.goldonce', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exponce', full_name='ExploreData.exponce', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='havedrop', full_name='ExploreData.havedrop', index=7,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=203,
)


_DSESTAGEEXPLORE = _descriptor.Descriptor(
  name='DseStageExplore',
  full_name='DseStageExplore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseStageExplore.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DseStageExplore.res', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='DseStageExplore.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gold', full_name='DseStageExplore.gold', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='DseStageExplore.exp', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='droplist', full_name='DseStageExplore.droplist', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=335,
)

_DSESTAGEEXPLORE.fields_by_name['info'].message_type = _EXPLOREDATA
_DSESTAGEEXPLORE.fields_by_name['droplist'].message_type = MDropList_pb2._MDROPLIST
DESCRIPTOR.message_types_by_name['ExploreData'] = _EXPLOREDATA
DESCRIPTOR.message_types_by_name['DseStageExplore'] = _DSESTAGEEXPLORE

ExploreData = _reflection.GeneratedProtocolMessageType('ExploreData', (_message.Message,), dict(
  DESCRIPTOR = _EXPLOREDATA,
  __module__ = 'DseStageExplore_pb2'
  # @@protoc_insertion_point(class_scope:ExploreData)
  ))
_sym_db.RegisterMessage(ExploreData)

DseStageExplore = _reflection.GeneratedProtocolMessageType('DseStageExplore', (_message.Message,), dict(
  DESCRIPTOR = _DSESTAGEEXPLORE,
  __module__ = 'DseStageExplore_pb2'
  # @@protoc_insertion_point(class_scope:DseStageExplore)
  ))
_sym_db.RegisterMessage(DseStageExplore)


# @@protoc_insertion_point(module_scope)
