# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseSpiritDevelop.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseSpiritDevelop.proto',
  package='',
  serialized_pb=_b('\n\x16\x44seSpiritDevelop.proto\"<\n\x10\x44seSpiritDevelop\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSESPIRITDEVELOP = _descriptor.Descriptor(
  name='DseSpiritDevelop',
  full_name='DseSpiritDevelop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DseSpiritDevelop.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='DseSpiritDevelop.action', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='DseSpiritDevelop.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['DseSpiritDevelop'] = _DSESPIRITDEVELOP

DseSpiritDevelop = _reflection.GeneratedProtocolMessageType('DseSpiritDevelop', (_message.Message,), dict(
  DESCRIPTOR = _DSESPIRITDEVELOP,
  __module__ = 'DseSpiritDevelop_pb2'
  # @@protoc_insertion_point(class_scope:DseSpiritDevelop)
  ))
_sym_db.RegisterMessage(DseSpiritDevelop)


# @@protoc_insertion_point(module_scope)
