# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseStageInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import StageData_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseStageInfo.proto',
  package='',
  serialized_pb=_b('\n\x12\x44seStageInfo.proto\x1a\x0fStageData.proto\"\x80\x01\n\x0b\x43hapterInfo\x12\x11\n\tchapterid\x18\x01 \x01(\x05\x12\x13\n\x0bnextstageid\x18\x02 \x01(\x05\x12\x0f\n\x07isaward\x18\x03 \x01(\x08\x12\x1d\n\tscenelist\x18\x04 \x03(\x0b\x32\n.ChildInfo\x12\x19\n\x11lastjuniorstageid\x18\x05 \x01(\x05\"_\n\tChildInfo\x12\x0f\n\x07sceneid\x18\x01 \x01(\x05\x12\x11\n\tscenestar\x18\x02 \x01(\x05\x12\x0f\n\x07isaward\x18\x03 \x01(\x08\x12\x1d\n\tstagelist\x18\x04 \x03(\x0b\x32\n.StageData\"?\n\x0c\x44seStageInfo\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12!\n\x0b\x63hapterinfo\x18\x02 \x01(\x0b\x32\x0c.ChapterInfo')
  ,
  dependencies=[StageData_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHAPTERINFO = _descriptor.Descriptor(
  name='ChapterInfo',
  full_name='ChapterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chapterid', full_name='ChapterInfo.chapterid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nextstageid', full_name='ChapterInfo.nextstageid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isaward', full_name='ChapterInfo.isaward', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scenelist', full_name='ChapterInfo.scenelist', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastjuniorstageid', full_name='ChapterInfo.lastjuniorstageid', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=168,
)


_CHILDINFO = _descriptor.Descriptor(
  name='ChildInfo',
  full_name='ChildInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sceneid', full_name='ChildInfo.sceneid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scenestar', full_name='ChildInfo.scenestar', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isaward', full_name='ChildInfo.isaward', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stagelist', full_name='ChildInfo.stagelist', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=265,
)


_DSESTAGEINFO = _descriptor.Descriptor(
  name='DseStageInfo',
  full_name='DseStageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseStageInfo.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chapterinfo', full_name='DseStageInfo.chapterinfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=330,
)

_CHAPTERINFO.fields_by_name['scenelist'].message_type = _CHILDINFO
_CHILDINFO.fields_by_name['stagelist'].message_type = StageData_pb2._STAGEDATA
_DSESTAGEINFO.fields_by_name['chapterinfo'].message_type = _CHAPTERINFO
DESCRIPTOR.message_types_by_name['ChapterInfo'] = _CHAPTERINFO
DESCRIPTOR.message_types_by_name['ChildInfo'] = _CHILDINFO
DESCRIPTOR.message_types_by_name['DseStageInfo'] = _DSESTAGEINFO

ChapterInfo = _reflection.GeneratedProtocolMessageType('ChapterInfo', (_message.Message,), dict(
  DESCRIPTOR = _CHAPTERINFO,
  __module__ = 'DseStageInfo_pb2'
  # @@protoc_insertion_point(class_scope:ChapterInfo)
  ))
_sym_db.RegisterMessage(ChapterInfo)

ChildInfo = _reflection.GeneratedProtocolMessageType('ChildInfo', (_message.Message,), dict(
  DESCRIPTOR = _CHILDINFO,
  __module__ = 'DseStageInfo_pb2'
  # @@protoc_insertion_point(class_scope:ChildInfo)
  ))
_sym_db.RegisterMessage(ChildInfo)

DseStageInfo = _reflection.GeneratedProtocolMessageType('DseStageInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSESTAGEINFO,
  __module__ = 'DseStageInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseStageInfo)
  ))
_sym_db.RegisterMessage(DseStageInfo)


# @@protoc_insertion_point(module_scope)
