# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseTownPatrolOpt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseTownPatrolOpt.proto',
  package='',
  serialized_pb=_b('\n\x16\x44seTownPatrolOpt.proto\x1a\x0fMDropList.proto\"\xbe\x01\n\x0eTownPatrolInfo\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x14\n\x0cpatrolspells\x18\x02 \x01(\x05\x12\x17\n\x0flastrecovertime\x18\x03 \x01(\t\x12\r\n\x05isbuy\x18\x04 \x01(\x08\x12\x11\n\tslatelist\x18\x05 \x03(\x05\x12\x10\n\x08\x63\x61nguess\x18\x06 \x01(\x08\x12\x11\n\tcanhoeing\x18\x07 \x01(\x08\x12\x13\n\x0b\x66inishtimes\x18\x08 \x01(\x05\x12\x14\n\x0c\x66inishreward\x18\t \x03(\x05\"\x85\x01\n\x11TownPatrolOneMove\x12\x10\n\x08slatenum\x18\x01 \x01(\x05\x12\x11\n\teventtype\x18\x02 \x01(\x05\x12\x1c\n\x08\x64roplist\x18\x03 \x01(\x0b\x32\n.MDropList\x12\x1c\n\x08\x66\x61rmland\x18\x04 \x01(\x0b\x32\n.MDropList\x12\x0f\n\x07getgold\x18\x05 \x01(\x05\"\xbd\x01\n\x10\x44seTownPatrolOpt\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03res\x18\x02 \x01(\x05\x12\r\n\x05param\x18\x03 \x01(\x05\x12\x10\n\x08guessres\x18\x04 \x01(\x05\x12\"\n\x0eoptiondroplist\x18\x05 \x01(\x0b\x32\n.MDropList\x12$\n\x08movelist\x18\x06 \x03(\x0b\x32\x12.TownPatrolOneMove\x12#\n\npatrolinfo\x18\x07 \x01(\x0b\x32\x0f.TownPatrolInfo')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TOWNPATROLINFO = _descriptor.Descriptor(
  name='TownPatrolInfo',
  full_name='TownPatrolInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='TownPatrolInfo.pos', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patrolspells', full_name='TownPatrolInfo.patrolspells', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastrecovertime', full_name='TownPatrolInfo.lastrecovertime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isbuy', full_name='TownPatrolInfo.isbuy', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slatelist', full_name='TownPatrolInfo.slatelist', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canguess', full_name='TownPatrolInfo.canguess', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canhoeing', full_name='TownPatrolInfo.canhoeing', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finishtimes', full_name='TownPatrolInfo.finishtimes', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finishreward', full_name='TownPatrolInfo.finishreward', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=234,
)


_TOWNPATROLONEMOVE = _descriptor.Descriptor(
  name='TownPatrolOneMove',
  full_name='TownPatrolOneMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slatenum', full_name='TownPatrolOneMove.slatenum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventtype', full_name='TownPatrolOneMove.eventtype', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='droplist', full_name='TownPatrolOneMove.droplist', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='farmland', full_name='TownPatrolOneMove.farmland', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getgold', full_name='TownPatrolOneMove.getgold', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=370,
)


_DSETOWNPATROLOPT = _descriptor.Descriptor(
  name='DseTownPatrolOpt',
  full_name='DseTownPatrolOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseTownPatrolOpt.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DseTownPatrolOpt.res', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='DseTownPatrolOpt.param', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guessres', full_name='DseTownPatrolOpt.guessres', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optiondroplist', full_name='DseTownPatrolOpt.optiondroplist', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='movelist', full_name='DseTownPatrolOpt.movelist', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patrolinfo', full_name='DseTownPatrolOpt.patrolinfo', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=562,
)

_TOWNPATROLONEMOVE.fields_by_name['droplist'].message_type = MDropList_pb2._MDROPLIST
_TOWNPATROLONEMOVE.fields_by_name['farmland'].message_type = MDropList_pb2._MDROPLIST
_DSETOWNPATROLOPT.fields_by_name['optiondroplist'].message_type = MDropList_pb2._MDROPLIST
_DSETOWNPATROLOPT.fields_by_name['movelist'].message_type = _TOWNPATROLONEMOVE
_DSETOWNPATROLOPT.fields_by_name['patrolinfo'].message_type = _TOWNPATROLINFO
DESCRIPTOR.message_types_by_name['TownPatrolInfo'] = _TOWNPATROLINFO
DESCRIPTOR.message_types_by_name['TownPatrolOneMove'] = _TOWNPATROLONEMOVE
DESCRIPTOR.message_types_by_name['DseTownPatrolOpt'] = _DSETOWNPATROLOPT

TownPatrolInfo = _reflection.GeneratedProtocolMessageType('TownPatrolInfo', (_message.Message,), dict(
  DESCRIPTOR = _TOWNPATROLINFO,
  __module__ = 'DseTownPatrolOpt_pb2'
  # @@protoc_insertion_point(class_scope:TownPatrolInfo)
  ))
_sym_db.RegisterMessage(TownPatrolInfo)

TownPatrolOneMove = _reflection.GeneratedProtocolMessageType('TownPatrolOneMove', (_message.Message,), dict(
  DESCRIPTOR = _TOWNPATROLONEMOVE,
  __module__ = 'DseTownPatrolOpt_pb2'
  # @@protoc_insertion_point(class_scope:TownPatrolOneMove)
  ))
_sym_db.RegisterMessage(TownPatrolOneMove)

DseTownPatrolOpt = _reflection.GeneratedProtocolMessageType('DseTownPatrolOpt', (_message.Message,), dict(
  DESCRIPTOR = _DSETOWNPATROLOPT,
  __module__ = 'DseTownPatrolOpt_pb2'
  # @@protoc_insertion_point(class_scope:DseTownPatrolOpt)
  ))
_sym_db.RegisterMessage(DseTownPatrolOpt)


# @@protoc_insertion_point(module_scope)
