# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseUserInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseUserInfo.proto',
  package='',
  serialized_pb=_b('\n\x11\x44seUserInfo.proto\"\xde\x01\n\x0ePlayerBaseInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x03 \x01(\x05\x12\x10\n\x08vipLevel\x18\x04 \x01(\x05\x12\x10\n\x08totalbuy\x18\x05 \x01(\x05\x12\x0c\n\x04head\x18\x06 \x01(\x05\x12\r\n\x05power\x18\x07 \x01(\x05\x12\x12\n\nsweeptimes\x18\x08 \x01(\x05\x12\x15\n\rscreenspirits\x18\t \x01(\x05\x12\x0b\n\x03uid\x18\n \x01(\t\x12\x15\n\rfreechattimes\x18\x0b \x01(\x05\x12\x12\n\nusedsuitid\x18\x0c \x01(\x05\"\xb8\x01\n\x0ePlayerCurrency\x12\x14\n\x0crechargecash\x18\x01 \x01(\x05\x12\x0c\n\x04\x63\x61sh\x18\x02 \x01(\x05\x12\x10\n\x08vitality\x18\x03 \x01(\x05\x12\x0c\n\x04gold\x18\x04 \x01(\t\x12\x12\n\nfriendship\x18\x05 \x01(\x05\x12\x0e\n\x06\x64\x65\x63ree\x18\x06 \x01(\x05\x12\x14\n\x0crefine_point\x18\x07 \x01(\x05\x12\x13\n\x0b\x61rena_point\x18\x08 \x01(\x05\x12\x13\n\x0bguild_point\x18\t \x01(\x05\"\x11\n\x0fMainAnnoncement\"s\n\x0b\x44seUserInfo\x12\x1d\n\x04info\x18\x01 \x01(\x0b\x32\x0f.PlayerBaseInfo\x12!\n\x08\x63urrency\x18\x02 \x01(\x0b\x32\x0f.PlayerCurrency\x12\"\n\x08\x61nnounce\x18\x03 \x01(\x0b\x32\x10.MainAnnoncement')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERBASEINFO = _descriptor.Descriptor(
  name='PlayerBaseInfo',
  full_name='PlayerBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PlayerBaseInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='PlayerBaseInfo.level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='PlayerBaseInfo.exp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vipLevel', full_name='PlayerBaseInfo.vipLevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalbuy', full_name='PlayerBaseInfo.totalbuy', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head', full_name='PlayerBaseInfo.head', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='PlayerBaseInfo.power', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sweeptimes', full_name='PlayerBaseInfo.sweeptimes', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='screenspirits', full_name='PlayerBaseInfo.screenspirits', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='PlayerBaseInfo.uid', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='freechattimes', full_name='PlayerBaseInfo.freechattimes', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usedsuitid', full_name='PlayerBaseInfo.usedsuitid', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=244,
)


_PLAYERCURRENCY = _descriptor.Descriptor(
  name='PlayerCurrency',
  full_name='PlayerCurrency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rechargecash', full_name='PlayerCurrency.rechargecash', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cash', full_name='PlayerCurrency.cash', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vitality', full_name='PlayerCurrency.vitality', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gold', full_name='PlayerCurrency.gold', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friendship', full_name='PlayerCurrency.friendship', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decree', full_name='PlayerCurrency.decree', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refine_point', full_name='PlayerCurrency.refine_point', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arena_point', full_name='PlayerCurrency.arena_point', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guild_point', full_name='PlayerCurrency.guild_point', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=431,
)


_MAINANNONCEMENT = _descriptor.Descriptor(
  name='MainAnnoncement',
  full_name='MainAnnoncement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=450,
)


_DSEUSERINFO = _descriptor.Descriptor(
  name='DseUserInfo',
  full_name='DseUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='DseUserInfo.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='DseUserInfo.currency', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='announce', full_name='DseUserInfo.announce', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=567,
)

_DSEUSERINFO.fields_by_name['info'].message_type = _PLAYERBASEINFO
_DSEUSERINFO.fields_by_name['currency'].message_type = _PLAYERCURRENCY
_DSEUSERINFO.fields_by_name['announce'].message_type = _MAINANNONCEMENT
DESCRIPTOR.message_types_by_name['PlayerBaseInfo'] = _PLAYERBASEINFO
DESCRIPTOR.message_types_by_name['PlayerCurrency'] = _PLAYERCURRENCY
DESCRIPTOR.message_types_by_name['MainAnnoncement'] = _MAINANNONCEMENT
DESCRIPTOR.message_types_by_name['DseUserInfo'] = _DSEUSERINFO

PlayerBaseInfo = _reflection.GeneratedProtocolMessageType('PlayerBaseInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERBASEINFO,
  __module__ = 'DseUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:PlayerBaseInfo)
  ))
_sym_db.RegisterMessage(PlayerBaseInfo)

PlayerCurrency = _reflection.GeneratedProtocolMessageType('PlayerCurrency', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERCURRENCY,
  __module__ = 'DseUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:PlayerCurrency)
  ))
_sym_db.RegisterMessage(PlayerCurrency)

MainAnnoncement = _reflection.GeneratedProtocolMessageType('MainAnnoncement', (_message.Message,), dict(
  DESCRIPTOR = _MAINANNONCEMENT,
  __module__ = 'DseUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:MainAnnoncement)
  ))
_sym_db.RegisterMessage(MainAnnoncement)

DseUserInfo = _reflection.GeneratedProtocolMessageType('DseUserInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSEUSERINFO,
  __module__ = 'DseUserInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseUserInfo)
  ))
_sym_db.RegisterMessage(DseUserInfo)


# @@protoc_insertion_point(module_scope)
