# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseUpdateSpiritInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DseSingleSpiritInfo_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseUpdateSpiritInfo.proto',
  package='',
  serialized_pb=_b('\n\x19\x44seUpdateSpiritInfo.proto\x1a\x19\x44seSingleSpiritInfo.proto\"=\n\x13\x44seUpdateSpiritInfo\x12&\n\x08soldiers\x18\x01 \x03(\x0b\x32\x14.DseSingleSpiritInfo')
  ,
  dependencies=[DseSingleSpiritInfo_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEUPDATESPIRITINFO = _descriptor.Descriptor(
  name='DseUpdateSpiritInfo',
  full_name='DseUpdateSpiritInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='soldiers', full_name='DseUpdateSpiritInfo.soldiers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=117,
)

_DSEUPDATESPIRITINFO.fields_by_name['soldiers'].message_type = DseSingleSpiritInfo_pb2._DSESINGLESPIRITINFO
DESCRIPTOR.message_types_by_name['DseUpdateSpiritInfo'] = _DSEUPDATESPIRITINFO

DseUpdateSpiritInfo = _reflection.GeneratedProtocolMessageType('DseUpdateSpiritInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSEUPDATESPIRITINFO,
  __module__ = 'DseUpdateSpiritInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseUpdateSpiritInfo)
  ))
_sym_db.RegisterMessage(DseUpdateSpiritInfo)


# @@protoc_insertion_point(module_scope)
