# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseUpdateStage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import StageData_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseUpdateStage.proto',
  package='',
  serialized_pb=_b('\n\x14\x44seUpdateStage.proto\x1a\x0fStageData.proto\"=\n\x0e\x44seUpdateStage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x1d\n\tstagelist\x18\x02 \x03(\x0b\x32\n.StageData')
  ,
  dependencies=[StageData_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEUPDATESTAGE = _descriptor.Descriptor(
  name='DseUpdateStage',
  full_name='DseUpdateStage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='DseUpdateStage.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stagelist', full_name='DseUpdateStage.stagelist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=102,
)

_DSEUPDATESTAGE.fields_by_name['stagelist'].message_type = StageData_pb2._STAGEDATA
DESCRIPTOR.message_types_by_name['DseUpdateStage'] = _DSEUPDATESTAGE

DseUpdateStage = _reflection.GeneratedProtocolMessageType('DseUpdateStage', (_message.Message,), dict(
  DESCRIPTOR = _DSEUPDATESTAGE,
  __module__ = 'DseUpdateStage_pb2'
  # @@protoc_insertion_point(class_scope:DseUpdateStage)
  ))
_sym_db.RegisterMessage(DseUpdateStage)


# @@protoc_insertion_point(module_scope)
