# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseUseItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MDropList_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseUseItem.proto',
  package='',
  serialized_pb=_b('\n\x10\x44seUseItem.proto\x1a\x0fMDropList.proto\"b\n\nDseUseItem\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\x18\n\x04list\x18\x04 \x01(\x0b\x32\n.MDropList\x12\x0f\n\x07msgType\x18\x05 \x01(\x05')
  ,
  dependencies=[MDropList_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEUSEITEM = _descriptor.Descriptor(
  name='DseUseItem',
  full_name='DseUseItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='DseUseItem.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='DseUseItem.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='DseUseItem.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list', full_name='DseUseItem.list', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='DseUseItem.msgType', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=135,
)

_DSEUSEITEM.fields_by_name['list'].message_type = MDropList_pb2._MDROPLIST
DESCRIPTOR.message_types_by_name['DseUseItem'] = _DSEUSEITEM

DseUseItem = _reflection.GeneratedProtocolMessageType('DseUseItem', (_message.Message,), dict(
  DESCRIPTOR = _DSEUSEITEM,
  __module__ = 'DseUseItem_pb2'
  # @@protoc_insertion_point(class_scope:DseUseItem)
  ))
_sym_db.RegisterMessage(DseUseItem)


# @@protoc_insertion_point(module_scope)
