# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DseUpdateEquipmentInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EquipmentInfo_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DseUpdateEquipmentInfo.proto',
  package='',
  serialized_pb=_b('\n\x1c\x44seUpdateEquipmentInfo.proto\x1a\x13\x45quipmentInfo.proto\"7\n\x16\x44seUpdateEquipmentInfo\x12\x1d\n\x05infos\x18\x01 \x03(\x0b\x32\x0e.EquipmentInfo')
  ,
  dependencies=[EquipmentInfo_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DSEUPDATEEQUIPMENTINFO = _descriptor.Descriptor(
  name='DseUpdateEquipmentInfo',
  full_name='DseUpdateEquipmentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='infos', full_name='DseUpdateEquipmentInfo.infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=108,
)

_DSEUPDATEEQUIPMENTINFO.fields_by_name['infos'].message_type = EquipmentInfo_pb2._EQUIPMENTINFO
DESCRIPTOR.message_types_by_name['DseUpdateEquipmentInfo'] = _DSEUPDATEEQUIPMENTINFO

DseUpdateEquipmentInfo = _reflection.GeneratedProtocolMessageType('DseUpdateEquipmentInfo', (_message.Message,), dict(
  DESCRIPTOR = _DSEUPDATEEQUIPMENTINFO,
  __module__ = 'DseUpdateEquipmentInfo_pb2'
  # @@protoc_insertion_point(class_scope:DseUpdateEquipmentInfo)
  ))
_sym_db.RegisterMessage(DseUpdateEquipmentInfo)


# @@protoc_insertion_point(module_scope)
