# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EquipmentInfoLite.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EquipmentInfoLite.proto',
  package='',
  serialized_pb=_b('\n\x17\x45quipmentInfoLite.proto\"8\n\x11\x45quipmentInfoLite\x12\x0b\n\x03oid\x18\x01 \x01(\t\x12\x16\n\x03pos\x18\x02 \x01(\x0e\x32\t.EquipPos*5\n\x08\x45quipPos\x12\n\n\x06WEAPON\x10\x01\x12\x08\n\x04HEAD\x10\x02\x12\t\n\x05\x43HEST\x10\x03\x12\x08\n\x04\x42OOT\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EQUIPPOS = _descriptor.EnumDescriptor(
  name='EquipPos',
  full_name='EquipPos',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WEAPON', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEAD', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHEST', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOT', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=85,
  serialized_end=138,
)
_sym_db.RegisterEnumDescriptor(_EQUIPPOS)

EquipPos = enum_type_wrapper.EnumTypeWrapper(_EQUIPPOS)
WEAPON = 1
HEAD = 2
CHEST = 3
BOOT = 4



_EQUIPMENTINFOLITE = _descriptor.Descriptor(
  name='EquipmentInfoLite',
  full_name='EquipmentInfoLite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oid', full_name='EquipmentInfoLite.oid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='EquipmentInfoLite.pos', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=83,
)

_EQUIPMENTINFOLITE.fields_by_name['pos'].enum_type = _EQUIPPOS
DESCRIPTOR.message_types_by_name['EquipmentInfoLite'] = _EQUIPMENTINFOLITE
DESCRIPTOR.enum_types_by_name['EquipPos'] = _EQUIPPOS

EquipmentInfoLite = _reflection.GeneratedProtocolMessageType('EquipmentInfoLite', (_message.Message,), dict(
  DESCRIPTOR = _EQUIPMENTINFOLITE,
  __module__ = 'EquipmentInfoLite_pb2'
  # @@protoc_insertion_point(class_scope:EquipmentInfoLite)
  ))
_sym_db.RegisterMessage(EquipmentInfoLite)


# @@protoc_insertion_point(module_scope)
