# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDropList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDropList.proto',
  package='',
  serialized_pb=_b('\n\x0fMDropList.proto\"8\n\tMDropData\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"&\n\tMDropList\x12\x19\n\x05\x64rops\x18\x01 \x03(\x0b\x32\n.MDropData')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MDROPDATA = _descriptor.Descriptor(
  name='MDropData',
  full_name='MDropData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MDropData.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='MDropData.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='MDropData.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=75,
)


_MDROPLIST = _descriptor.Descriptor(
  name='MDropList',
  full_name='MDropList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='drops', full_name='MDropList.drops', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=115,
)

_MDROPLIST.fields_by_name['drops'].message_type = _MDROPDATA
DESCRIPTOR.message_types_by_name['MDropData'] = _MDROPDATA
DESCRIPTOR.message_types_by_name['MDropList'] = _MDROPLIST

MDropData = _reflection.GeneratedProtocolMessageType('MDropData', (_message.Message,), dict(
  DESCRIPTOR = _MDROPDATA,
  __module__ = 'MDropList_pb2'
  # @@protoc_insertion_point(class_scope:MDropData)
  ))
_sym_db.RegisterMessage(MDropData)

MDropList = _reflection.GeneratedProtocolMessageType('MDropList', (_message.Message,), dict(
  DESCRIPTOR = _MDROPLIST,
  __module__ = 'MDropList_pb2'
  # @@protoc_insertion_point(class_scope:MDropList)
  ))
_sym_db.RegisterMessage(MDropList)


# @@protoc_insertion_point(module_scope)
