# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MItem.proto',
  package='',
  serialized_pb=_b('\n\x0bMItem.proto\"$\n\x05MItem\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MITEM = _descriptor.Descriptor(
  name='MItem',
  full_name='MItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='MItem.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='MItem.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['MItem'] = _MITEM

MItem = _reflection.GeneratedProtocolMessageType('MItem', (_message.Message,), dict(
  DESCRIPTOR = _MITEM,
  __module__ = 'MItem_pb2'
  # @@protoc_insertion_point(class_scope:MItem)
  ))
_sym_db.RegisterMessage(MItem)


# @@protoc_insertion_point(module_scope)
