# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RankPlayer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RankPlayer.proto',
  package='',
  serialized_pb=_b('\n\x10RankPlayer.proto\"\xab\x01\n\nRankPlayer\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x0c\n\x04head\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0c\n\x04rank\x18\x06 \x01(\x05\x12\x11\n\tguildname\x18\x07 \x01(\t\x12\r\n\x05param\x18\x08 \x01(\x05\x12\x10\n\x08\x62\x65stskin\x18\t \x01(\x05\x12\x14\n\x0c\x62\x65setupgrade\x18\n \x01(\x05\x12\r\n\x05skins\x18\x0b \x03(\x05\"A\n\x0eRankPlayerList\x12\x1d\n\x08ranklist\x18\x01 \x03(\x0b\x32\x0b.RankPlayer\x12\x10\n\x08selfrank\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RANKPLAYER = _descriptor.Descriptor(
  name='RankPlayer',
  full_name='RankPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='RankPlayer.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='RankPlayer.level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='head', full_name='RankPlayer.head', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='RankPlayer.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank', full_name='RankPlayer.rank', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guildname', full_name='RankPlayer.guildname', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='RankPlayer.param', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bestskin', full_name='RankPlayer.bestskin', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='besetupgrade', full_name='RankPlayer.besetupgrade', index=8,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skins', full_name='RankPlayer.skins', index=9,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=192,
)


_RANKPLAYERLIST = _descriptor.Descriptor(
  name='RankPlayerList',
  full_name='RankPlayerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ranklist', full_name='RankPlayerList.ranklist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='selfrank', full_name='RankPlayerList.selfrank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=259,
)

_RANKPLAYERLIST.fields_by_name['ranklist'].message_type = _RANKPLAYER
DESCRIPTOR.message_types_by_name['RankPlayer'] = _RANKPLAYER
DESCRIPTOR.message_types_by_name['RankPlayerList'] = _RANKPLAYERLIST

RankPlayer = _reflection.GeneratedProtocolMessageType('RankPlayer', (_message.Message,), dict(
  DESCRIPTOR = _RANKPLAYER,
  __module__ = 'RankPlayer_pb2'
  # @@protoc_insertion_point(class_scope:RankPlayer)
  ))
_sym_db.RegisterMessage(RankPlayer)

RankPlayerList = _reflection.GeneratedProtocolMessageType('RankPlayerList', (_message.Message,), dict(
  DESCRIPTOR = _RANKPLAYERLIST,
  __module__ = 'RankPlayer_pb2'
  # @@protoc_insertion_point(class_scope:RankPlayerList)
  ))
_sym_db.RegisterMessage(RankPlayerList)


# @@protoc_insertion_point(module_scope)
