# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShopUnit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ShopUnit.proto',
  package='',
  serialized_pb=_b('\n\x0eShopUnit.proto\")\n\x08ShopUnit\x12\x0e\n\x06shopid\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SHOPUNIT = _descriptor.Descriptor(
  name='ShopUnit',
  full_name='ShopUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shopid', full_name='ShopUnit.shopid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='ShopUnit.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['ShopUnit'] = _SHOPUNIT

ShopUnit = _reflection.GeneratedProtocolMessageType('ShopUnit', (_message.Message,), dict(
  DESCRIPTOR = _SHOPUNIT,
  __module__ = 'ShopUnit_pb2'
  # @@protoc_insertion_point(class_scope:ShopUnit)
  ))
_sym_db.RegisterMessage(ShopUnit)


# @@protoc_insertion_point(module_scope)
