# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StageData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StageData.proto',
  package='',
  serialized_pb=_b('\n\x0fStageData.proto\"P\n\tStageData\x12\x0f\n\x07stageid\x18\x01 \x01(\x05\x12\x0c\n\x04star\x18\x02 \x01(\x05\x12\x12\n\ntodaytimes\x18\x03 \x01(\x05\x12\x10\n\x08todaybuy\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STAGEDATA = _descriptor.Descriptor(
  name='StageData',
  full_name='StageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stageid', full_name='StageData.stageid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='star', full_name='StageData.star', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='todaytimes', full_name='StageData.todaytimes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='todaybuy', full_name='StageData.todaybuy', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['StageData'] = _STAGEDATA

StageData = _reflection.GeneratedProtocolMessageType('StageData', (_message.Message,), dict(
  DESCRIPTOR = _STAGEDATA,
  __module__ = 'StageData_pb2'
  # @@protoc_insertion_point(class_scope:StageData)
  ))
_sym_db.RegisterMessage(StageData)


# @@protoc_insertion_point(module_scope)
