#ifndef _MESSAGEDEF_H_
#define _MESSAGEDEF_H_
//该文件为使用工具自动生成，请不要在文件中修改，如需要修改，请与sskylin联系。
enum S2C_EVENT
{
	S2C_EVENT_BASE = 511,
	S2C_DseAuthState,		//DseAuthState
	S2C_DseBattleStart,		//DseBattleStart
	S2C_DseCombineProto,		//DseCombineProto
	S2C_DseHeartbeat,		//DseHeartbeat
	S2C_DseResetLeaderResult,		//DseResetLeaderResult
	S2C_DseSingleSpiritInfo,		//DseSingleSpiritInfo
	S2C_DseFormationInfo,		//DseFormationInfo
	S2C_DseAllSpiritInfo,		//DseAllSpiritInfo
	S2C_DseBattleOpt,		//DseBattleOpt
	S2C_DseUserInfo,		//DseUserInfo
	S2C_DseStageInfo,		//DseStageInfo
	S2C_DseStageAward,		//DseStageAward
	S2C_DseStageExplore,		//DseStageExplore
	S2C_DseItemChange,		//DseItemChange
	S2C_DseStorageList,		//DseStorageList
	S2C_DseUseItem,		//DseUseItem
	S2C_DseUpdateStage,		//DseUpdateStage
	S2C_DseBattleSweep,		//DseBattleSweep
	S2C_DseMainScreenReady,		//DseMainScreenReady
	S2C_DseShopOpt,		//DseShopOpt
	S2C_DseDecreeShopOpt,		//DseDecreeShopOpt
	S2C_DseStageReset,		//DseStageReset
	S2C_DseUpdateSpiritInfo,		//DseUpdateSpiritInfo
	S2C_DseSummon,		//DseSummon
	S2C_DseSummonInterface,		//DseSummonInterface
	S2C_DseSpiritDevelop,		//DseSpiritDevelop
	S2C_DseSwitchFormation,		//DseSwitchFormation
	S2C_DseCombineSpiritDebris,		//DseCombineSpiritDebris
	S2C_DseSpiritDebrisList,		//DseSpiritDebrisList
	S2C_DseCombineEquipmentDebris,		//DseCombineEquipmentDebris
	S2C_DseEquipmentDebrisList,		//DseEquipmentDebrisList
	S2C_DseAllEquipmentInfo,		//DseAllEquipmentInfo
	S2C_DseUpdateEquipmentInfo,		//DseUpdateEquipmentInfo
	S2C_DseEquipmentGearUp,		//DseEquipmentGearUp
	S2C_DseEquipmentEnhance,		//DseEquipmentEnhance
	S2C_DseEquipmentRefine,		//DseEquipmentRefine
	S2C_DseTownPatrolOpt,		//DseTownPatrolOpt
	S2C_DseDevilTowerOpt,		//DseDevilTowerOpt
	S2C_DseMailOpt,		//DseMailOpt
	S2C_DseChangeSpiritSkin,		//DseChangeSpiritSkin
	S2C_DseReformInfo,		//DseReformInfo
	S2C_DseInstituteOpt,		//DseInstituteOpt
	S2C_DseDugeonOpt,		//DseDugeonOpt
	S2C_DseRankList,		//DseRankList
	S2C_DseArenaOpt,		//DseArenaOpt
	S2C_DseReforgeEquip,		//DseReforgeEquip
	S2C_DseReforgeSpirit,		//DseReforgeSpirit
	S2C_DseDailyMissionOpt,		//DseDailyMissionOpt
	S2C_DseChatMsg,		//DseChatMsg
	S2C_DseChatMsgAll,		//DseChatMsgAll
	S2C_DseChat,		//DseChat
	S2C_DseGuildCreate,		//DseGuildCreate
	S2C_DseGuildApplyJoin,		//DseGuildApplyJoin
	S2C_DseGuildManageApply,		//DseGuildManageApply
	S2C_DseGuildAdjustGrade,		//DseGuildAdjustGrade
	S2C_DseGuildDismiss,		//DseGuildDismiss
	S2C_DseGuildKickMember,		//DseGuildKickMember
	S2C_DseGuildQuit,		//DseGuildQuit
	S2C_DseGuildEdit,		//DseGuildEdit
	S2C_DseGuildDonate,		//DseGuildDonate
	S2C_DseGuildChangeApplyRule,		//DseGuildChangeApplyRule
	S2C_DseSetRole,		//DseSetRole
	S2C_DseSuitList,		//DseSuitList
	S2C_DseQueryUserInfo,		//DseQueryUserInfo
	S2C_DseDailyActivityOpt,		//DseDailyActivityOpt
	S2C_DseBlackListOpt,		//DseBlackListOpt
	S2C_DseDailyOlineAwardData,		//DseDailyOlineAwardData
	S2C_DseDailyOlineGetAward,		//DseDailyOlineGetAward
	S2C_DseGuildLeaveMessage,		//DseGuildLeaveMessage
	S2C_DseGuildData,		//DseGuildData
};
enum C2S_EVENT
{
	C2S_EVENT_BASE = 2047,
	C2S_DceBattleStart,		//DceBattleStart
	C2S_DceCombineProto,		//DceCombineProto
	C2S_DceHeartbeat,		//DceHeartbeat
	C2S_DceResetLeader,		//DceResetLeader
	C2S_DceShowSpiritInfo,		//DceShowSpiritInfo
	C2S_DceShowFormationInfo,		//DceShowFormationInfo
	C2S_DceSwitchFormation,		//DceSwitchFormation
	C2S_DceShowSingleSpiritInfo,		//DceShowSingleSpiritInfo
	C2S_DceBattleOpt,		//DceBattleOpt
	C2S_DceUserInfo,		//DceUserInfo
	C2S_DceStageInfo,		//DceStageInfo
	C2S_DceStageAward,		//DceStageAward
	C2S_DceStageExplore,		//DceStageExplore
	C2S_DceStorageList,		//DceStorageList
	C2S_DceUseItem,		//DceUseItem
	C2S_DceBattleSweep,		//DceBattleSweep
	C2S_DceShopOpt,		//DceShopOpt
	C2S_DceDecreeShopOpt,		//DceDecreeShopOpt
	C2S_DceStageReset,		//DceStageReset
	C2S_DceSummon,		//DceSummon
	C2S_DceSummonInterface,		//DceSummonInterface
	C2S_DceSpiritDevelop,		//DceSpiritDevelop
	C2S_DceCombineSpiritDebris,		//DceCombineSpiritDebris
	C2S_DceSpiritDebrisList,		//DceSpiritDebrisList
	C2S_DceCombineEquipmentDebris,		//DceCombineEquipmentDebris
	C2S_DceEquipmentDebrisList,		//DceEquipmentDebrisList
	C2S_DceAllEquipmentInfo,		//DceAllEquipmentInfo
	C2S_DceEquipmentGearUp,		//DceEquipmentGearUp
	C2S_DceEquipmentEnhance,		//DceEquipmentEnhance
	C2S_DceEquipmentRefine,		//DceEquipmentRefine
	C2S_DceTownPatrolOpt,		//DceTownPatrolOpt
	C2S_DceDevilTowerOpt,		//DceDevilTowerOpt
	C2S_DceMailOpt,		//DceMailOpt
	C2S_DceChangeSpiritSkin,		//DceChangeSpiritSkin
	C2S_DceInstituteOpt,		//DceInstituteOpt
	C2S_DceDugeonOpt,		//DceDugeonOpt
	C2S_DceRankList,		//DceRankList
	C2S_DceArenaOpt,		//DceArenaOpt
	C2S_DceReforgeEquip,		//DceReforgeEquip
	C2S_DceReforgeSpirit,		//DceReforgeSpirit
	C2S_DceDailyMissionOpt,		//DceDailyMissionOpt
	C2S_DceChat,		//DceChat
	C2S_DceGuildCreate,		//DceGuildCreate
	C2S_DceGuildApplyJoin,		//DceGuildApplyJoin
	C2S_DceGuildManageApply,		//DceGuildManageApply
	C2S_DceGuildAdjustGrade,		//DceGuildAdjustGrade
	C2S_DceGuildDismiss,		//DceGuildDismiss
	C2S_DceGuildKickMember,		//DceGuildKickMember
	C2S_DceGuildQuit,		//DceGuildQuit
	C2S_DceGuildEdit,		//DceGuildEdit
	C2S_DceGuildDonate,		//DceGuildDonate
	C2S_DceGuildChangeApplyRule,		//DceGuildChangeApplyRule
	C2S_DceSetRole,		//DceSetRole
	C2S_DceSuitList,		//DceSuitList
	C2S_DceQueryUserInfo,		//DceQueryUserInfo
	C2S_DceDailyActivityOpt,		//DceDailyActivityOpt
	C2S_DceBlackListOpt,		//DceBlackListOpt
	C2S_DceDailyOlineAwardData,		//DceDailyOlineAwardData
	C2S_DceDailyOlineGetAward,		//DceDailyOlineGetAward
	C2S_DceGuildLeaveMessage,		//DceGuildLeaveMessage
	C2S_DceGuildData,		//DceGuildData
};
#endif
